var searchData=
[
  ['base',['Base',['../class_seven_zip_reduced_1_1_compression_1_1_l_z_m_a_1_1_base.html',1,'SevenZipReduced::Compression::LZMA']]],
  ['batchresizeitem',['BatchResizeItem',['../class_image_resizer_1_1_plugins_1_1_batch_zipper_1_1_batch_resize_item.html',1,'ImageResizer::Plugins::BatchZipper']]],
  ['batchresizemanager',['BatchResizeManager',['../class_image_resizer_1_1_plugins_1_1_batch_zipper_1_1_batch_resize_manager.html',1,'ImageResizer::Plugins::BatchZipper']]],
  ['batchresizesettings',['BatchResizeSettings',['../class_image_resizer_1_1_plugins_1_1_batch_zipper_1_1_batch_resize_settings.html',1,'ImageResizer::Plugins::BatchZipper']]],
  ['batchresizeworker',['BatchResizeWorker',['../class_image_resizer_1_1_plugins_1_1_batch_zipper_1_1_batch_resize_worker.html',1,'ImageResizer::Plugins::BatchZipper']]],
  ['bintree',['BinTree',['../class_seven_zip_reduced_1_1_compression_1_1_l_z_1_1_bin_tree.html',1,'SevenZipReduced::Compression::LZ']]],
  ['bitdecoder',['BitDecoder',['../struct_seven_zip_reduced_1_1_compression_1_1_range_coder_1_1_bit_decoder.html',1,'SevenZipReduced::Compression::RangeCoder']]],
  ['bitencoder',['BitEncoder',['../struct_seven_zip_reduced_1_1_compression_1_1_range_coder_1_1_bit_encoder.html',1,'SevenZipReduced::Compression::RangeCoder']]],
  ['bitmaptag',['BitmapTag',['../class_image_resizer_1_1_resizing_1_1_bitmap_tag.html',1,'ImageResizer::Resizing']]],
  ['bittreedecoder',['BitTreeDecoder',['../struct_seven_zip_reduced_1_1_compression_1_1_range_coder_1_1_bit_tree_decoder.html',1,'SevenZipReduced::Compression::RangeCoder']]],
  ['bittreeencoder',['BitTreeEncoder',['../struct_seven_zip_reduced_1_1_compression_1_1_range_coder_1_1_bit_tree_encoder.html',1,'SevenZipReduced::Compression::RangeCoder']]],
  ['boundingbox',['BoundingBox',['../class_image_resizer_1_1_plugins_1_1_pdf_renderer_1_1_ghostscript_1_1_bounding_box.html',1,'ImageResizer::Plugins::PdfRenderer::Ghostscript']]],
  ['boundingboxfinder',['BoundingBoxFinder',['../class_image_resizer_1_1_plugins_1_1_whitespace_trimmer_1_1_bounding_box_finder.html',1,'ImageResizer::Plugins::WhitespaceTrimmer']]],
  ['boxedges',['BoxEdges',['../class_image_resizer_1_1_box_edges.html',1,'ImageResizer']]],
  ['boxpadding',['BoxPadding',['../class_image_resizer_1_1_resizing_1_1_box_padding.html',1,'ImageResizer::Resizing']]],
  ['builderextension',['BuilderExtension',['../class_image_resizer_1_1_resizing_1_1_builder_extension.html',1,'ImageResizer::Resizing']]],
  ['buildtypeattribute',['BuildTypeAttribute',['../class_image_resizer_1_1_util_1_1_build_type_attribute.html',1,'ImageResizer::Util']]],
  ['bundleattribute',['BundleAttribute',['../class_image_resizer_1_1_util_1_1_bundle_attribute.html',1,'ImageResizer::Util']]]
];
