var searchData=
[
  ['watermarkplugin',['WatermarkPlugin',['../class_image_resizer_1_1_plugins_1_1_watermark_1_1_watermark_plugin.html',1,'ImageResizer::Plugins::Watermark']]],
  ['webconfigwriter',['WebConfigWriter',['../class_image_resizer_1_1_plugins_1_1_disk_cache_1_1_web_config_writer.html',1,'ImageResizer::Plugins::DiskCache']]],
  ['webpdecoderplugin',['WebPDecoderPlugin',['../class_image_resizer_1_1_plugins_1_1_web_p_decoder_1_1_web_p_decoder_plugin.html',1,'ImageResizer::Plugins::WebPDecoder']]],
  ['webpencoderplugin',['WebPEncoderPlugin',['../class_image_resizer_1_1_plugins_1_1_web_p_encoder_1_1_web_p_encoder_plugin.html',1,'ImageResizer::Plugins::WebPEncoder']]],
  ['whitespacetrimmerplugin',['WhitespaceTrimmerPlugin',['../class_image_resizer_1_1_plugins_1_1_whitespace_trimmer_1_1_whitespace_trimmer_plugin.html',1,'ImageResizer::Plugins::WhitespaceTrimmer']]],
  ['wicbitmappadder',['WicBitmapPadder',['../class_image_resizer_1_1_plugins_1_1_wic_1_1_wic_bitmap_padder.html',1,'ImageResizer::Plugins::Wic']]],
  ['wicbitmappattern',['WICBitmapPattern',['../struct_image_resizer_1_1_plugins_1_1_wic_1_1_interop_services_1_1_com_types_1_1_w_i_c_bitmap_pattern.html',1,'ImageResizer::Plugins::Wic::InteropServices::ComTypes']]],
  ['wicbuilderplugin',['WicBuilderPlugin',['../class_image_resizer_1_1_plugins_1_1_wic_builder_1_1_wic_builder_plugin.html',1,'ImageResizer::Plugins::WicBuilder']]],
  ['wicdecoderplugin',['WicDecoderPlugin',['../class_image_resizer_1_1_plugins_1_1_wic_decoder_1_1_wic_decoder_plugin.html',1,'ImageResizer::Plugins::WicDecoder']]],
  ['wicencoderplugin',['WicEncoderPlugin',['../class_image_resizer_1_1_plugins_1_1_wic_encoder_1_1_wic_encoder_plugin.html',1,'ImageResizer::Plugins::WicEncoder']]],
  ['wicimagingfactory',['WICImagingFactory',['../class_image_resizer_1_1_plugins_1_1_wic_1_1_interop_services_1_1_com_types_1_1_w_i_c_imaging_factory.html',1,'ImageResizer::Plugins::Wic::InteropServices::ComTypes']]],
  ['wicmetadataheader',['WICMetadataHeader',['../struct_image_resizer_1_1_plugins_1_1_wic_1_1_interop_services_1_1_com_types_1_1_w_i_c_metadata_header.html',1,'ImageResizer::Plugins::Wic::InteropServices::ComTypes']]],
  ['wicmetadatapattern',['WICMetadataPattern',['../struct_image_resizer_1_1_plugins_1_1_wic_1_1_interop_services_1_1_com_types_1_1_w_i_c_metadata_pattern.html',1,'ImageResizer::Plugins::Wic::InteropServices::ComTypes']]],
  ['wicrawcapabilitiesinfo',['WICRawCapabilitiesInfo',['../struct_image_resizer_1_1_plugins_1_1_wic_1_1_interop_services_1_1_com_types_1_1_w_i_c_raw_capabilities_info.html',1,'ImageResizer::Plugins::Wic::InteropServices::ComTypes']]],
  ['wicrawtonecurve',['WICRawToneCurve',['../struct_image_resizer_1_1_plugins_1_1_wic_1_1_interop_services_1_1_com_types_1_1_w_i_c_raw_tone_curve.html',1,'ImageResizer::Plugins::Wic::InteropServices::ComTypes']]],
  ['wicrawtonecurvepoint',['WICRawToneCurvePoint',['../struct_image_resizer_1_1_plugins_1_1_wic_1_1_interop_services_1_1_com_types_1_1_w_i_c_raw_tone_curve_point.html',1,'ImageResizer::Plugins::Wic::InteropServices::ComTypes']]],
  ['wicrect',['WICRect',['../class_image_resizer_1_1_plugins_1_1_wic_1_1_interop_services_1_1_com_types_1_1_w_i_c_rect.html',1,'ImageResizer::Plugins::Wic::InteropServices::ComTypes']]],
  ['wpfbuilderextensions',['WpfBuilderExtensions',['../class_image_resizer_1_1_plugins_1_1_wpf_builder_1_1_wpf_builder_extensions.html',1,'ImageResizer::Plugins::WpfBuilder']]],
  ['wpfbuilderplugin',['WpfBuilderPlugin',['../class_image_resizer_1_1_plugins_1_1_wpf_builder_1_1_wpf_builder_plugin.html',1,'ImageResizer::Plugins::WpfBuilder']]],
  ['wpfencoderplugin',['WpfEncoderPlugin',['../class_image_resizer_1_1_plugins_1_1_wpf_builder_1_1_wpf_encoder_plugin.html',1,'ImageResizer::Plugins::WpfBuilder']]],
  ['wpfimagesettings',['WpfImageSettings',['../class_image_resizer_1_1_plugins_1_1_wpf_builder_1_1_wpf_image_settings.html',1,'ImageResizer::Plugins::WpfBuilder']]]
];
