ImageResizer: ImageResizer.ExtensionMethods.NameValueCollectionExtensions Class Reference
ImageResizer.ExtensionMethods.NameValueCollectionExtensions Class Reference
Static Public Member Functions
static T Get< T > (NameValueCollection t, string name)
Provides culture-invariant parsing of int, double, float, bool, and enum values.
static T Get< T > (NameValueCollection q, string name, T?defaultValue)
Provides culture-invariant parsing of int, double, float, bool, and enum values.
static T Get< T > (NameValueCollection q, string name, T defaultValue)
Provides culture-invariant parsing of int, double, float, bool, and enum values.
static T ParsePrimitive< T > (string value, T?defaultValue)
Provides culture-invariant parsing of int, double, float, bool, and enum values.
static string SerializePrimitive< T > (T?val)
static NameValueCollection SetAsString< T > (NameValueCollection q, string name, T val)
Serializes the given value by calling .ToString(). If the value is null, the key is removed.
static NameValueCollection Set< T > (NameValueCollection q, string name, T?val)
Provides culture-invariant serialization of value types, in lower case for querystring readability. Setting a key to null removes it.
static T[] GetList< T > (NameValueCollection q, string name, T?fallbackValue, params int[] allowedSizes)
static T[] ParseList< T > (string text, T?fallbackValue, params int[] allowedSizes)
Parses a comma-delimited list of primitive values. If there are unparsable items in the list, they will be replaced with 'fallbackValue'. If fallbackValue is null, the function will return null.
static NameValueCollection SetList< T > (NameValueCollection q, string name, T[] values, bool throwExceptions, params int[] allowedSizes)
static bool IsOneSpecified (NameValueCollection q, params string[] keys)
Returns true if any of the specified keys contain a value.
static NameValueCollection Normalize (NameValueCollection q, string primary, string secondary)
Normalizes a command that has two possible names. If either of the commands has a null or empty value, those keys are removed. If both the the primary and secondary are present, the secondary is removed. Otherwise, the secondary is renamed to the primary name.
static NameValueCollection Keep (NameValueCollection q, params string[] keysToKeep)
Creates and returns a new NameValueCollection instance that contains only the specified keys from the current collection.
Detailed Description
Definition at line 10 of file NameValueCollection.cs.
Member Function Documentation
static T ImageResizer.ExtensionMethods.NameValueCollectionExtensions.Get< T > (NameValueCollection t, string name) [inline, static]
Provides culture-invariant parsing of int, double, float, bool, and enum values.
Template Parameters:
T
Parameters:
t
name
Returns:
Type Constraints
T : struct
T : IConvertible
Definition at line 22 of file NameValueCollection.cs.
                                                                            : struct, IConvertible {
            return Get<T>(t, name, null);
        }
static T ImageResizer.ExtensionMethods.NameValueCollectionExtensions.Get< T > (NameValueCollection q, string name, T? defaultValue) [inline, static]
Provides culture-invariant parsing of int, double, float, bool, and enum values.
Template Parameters:
T
Parameters:
q
name
defaultValue
Returns:
Type Constraints
T : struct
T : IConvertible
Definition at line 33 of file NameValueCollection.cs.
                                                                                            :struct, IConvertible{
            return ParsePrimitive<T>(q[name],defaultValue);
        }
static T ImageResizer.ExtensionMethods.NameValueCollectionExtensions.Get< T > (NameValueCollection q, string name, T defaultValue) [inline, static]
Provides culture-invariant parsing of int, double, float, bool, and enum values.
Template Parameters:
T
Parameters:
q
name
defaultValue
Returns:
Type Constraints
T : struct
T : IConvertible
Definition at line 44 of file NameValueCollection.cs.
                                                                                           : struct, IConvertible {
            return ParsePrimitive<T>(q[name], defaultValue).Value;
        }
static bool ImageResizer.ExtensionMethods.NameValueCollectionExtensions.IsOneSpecified (NameValueCollection q, params string[] keys) [inline, static]
Returns true if any of the specified keys contain a value.
Parameters:
q
keys
Returns:
Definition at line 202 of file NameValueCollection.cs.
Referenced by ImageResizer.ResizeSettings.WasOneSpecified().
{
            foreach (String s in keys) if (!string.IsNullOrEmpty(q[s])) return true;
            return false;
        }
static NameValueCollection ImageResizer.ExtensionMethods.NameValueCollectionExtensions.Keep (NameValueCollection q, params string[] keysToKeep) [inline, static]
Creates and returns a new NameValueCollection instance that contains only the specified keys from the current collection.
Parameters:
q
keysToKeep
Returns:
Definition at line 239 of file NameValueCollection.cs.
Referenced by ImageResizer.Util.PathUtils.FilterQueryString().
{
            NameValueCollection c = new NameValueCollection();
            foreach (string s in keysToKeep)
                if (q[s] != null) c[s] = q[s];
            return c;
        }
static NameValueCollection ImageResizer.ExtensionMethods.NameValueCollectionExtensions.Normalize (NameValueCollection q, string primary, string secondary) [inline, static]
Normalizes a command that has two possible names. If either of the commands has a null or empty value, those keys are removed. If both the the primary and secondary are present, the secondary is removed. Otherwise, the secondary is renamed to the primary name.
Parameters:
primary
secondary
Definition at line 217 of file NameValueCollection.cs.
Referenced by ImageResizer.ResizeSettings.Normalize().
{
            //Get rid of null and empty values.
            if (string.IsNullOrEmpty(q[primary])) q.Remove(primary);
            if (string.IsNullOrEmpty(q[secondary])) q.Remove(secondary);
            //Our job is done if no secondary value exists.
            if (q[secondary] == null) return q;
            else {
                //Otherwise, we have to resolve it
                //No primary value? copy the secondary one. Otherwise leave it be
                if (q[primary] == null) q[primary] = q[secondary];
                //In either case, we now have a duplicate to remove
                q.Remove(secondary);
            }
            return q;
        }
static T [] ImageResizer.ExtensionMethods.NameValueCollectionExtensions.ParseList< T > (string text, T? fallbackValue, params int[] allowedSizes) [inline, static]
Parses a comma-delimited list of primitive values. If there are unparsable items in the list, they will be replaced with 'fallbackValue'. If fallbackValue is null, the function will return null.
Template Parameters:
T
Parameters:
text
fallbackValue
allowedSizes
Returns:
Type Constraints
T : struct
T : IConvertible
Definition at line 149 of file NameValueCollection.cs.
                                                                                                         : struct, IConvertible {
            if (text == null) return null;
            text = text.Trim(' ', '(', ')', ','); //Trim parenthesis, commas, and spaces
            if (text.Length == 0) return null;
            string[] parts = text.Split(new char[] { ',' }, StringSplitOptions.None);
            //Verify the array is of an accepted size if any are specified
            bool foundCount = allowedSizes.Length == 0;
            foreach (int c in allowedSizes) if (c == parts.Length) foundCount = true;
            if (!foundCount) return null;
            //Parse the array
            var vals = new T[parts.Length];
            for (var i = 0; i < parts.Length; i++) {
                var v = ParsePrimitive<T>(parts[i], fallbackValue);
                if (v == null) return null;
                vals[i] = v.Value;
            }
            return vals;
        }
static T ImageResizer.ExtensionMethods.NameValueCollectionExtensions.ParsePrimitive< T > (string value, T? defaultValue) [inline, static]
Provides culture-invariant parsing of int, double, float, bool, and enum values.
Template Parameters:
T
Parameters:
value
defaultValue
Returns:
Type Constraints
T : struct
T : IConvertible
Definition at line 56 of file NameValueCollection.cs.
                                                                                  : struct,IConvertible {
            if (value == null) return defaultValue;
            value = value.Trim(); //Trim whitespace
            if (value.Length == 0) return defaultValue;
            Type t = typeof(T);
            if (t == typeof(byte)) {
                byte temp = 0;
                if (byte.TryParse(value, NumberStyles.Integer, NumberFormatInfo.InvariantInfo, out temp)) return temp as T?;
            } else if (t == typeof(int)) {
                int temp = 0;
                if (int.TryParse(value, NumberStyles.Integer, NumberFormatInfo.InvariantInfo, out temp)) return temp as T?;
            } else if (t == typeof(double)) {
                double temp = 0;
                if (double.TryParse(value, floatingPointStyle, NumberFormatInfo.InvariantInfo, out temp)) return temp as T?;
            } else if (t == typeof(float)) {
                float temp = 0;
                if (float.TryParse(value, floatingPointStyle, NumberFormatInfo.InvariantInfo, out temp)) return temp as T?;
            } else if (t == typeof(bool)) {
                string s = value;
                if ("true".Equals(s, StringComparison.OrdinalIgnoreCase) ||
                     "1".Equals(s, StringComparison.OrdinalIgnoreCase) ||
                     "yes".Equals(s, StringComparison.OrdinalIgnoreCase) ||
                     "on".Equals(s, StringComparison.OrdinalIgnoreCase)) return true as T?;
                else if ("false".Equals(s, StringComparison.OrdinalIgnoreCase) ||
                    "0".Equals(s, StringComparison.OrdinalIgnoreCase) ||
                    "no".Equals(s, StringComparison.OrdinalIgnoreCase) ||
                    "off".Equals(s, StringComparison.OrdinalIgnoreCase)) return false as T?;
            } else if (t.IsEnum) {
                T? val = EnumExtensions.Parse<T>(value); //Support EnumString values
                if (val.HasValue) return val;
            } else {
                T? val =  value as T?; //Just try casting
                if (val.HasValue) return val;
            }
            return defaultValue;
        }
static NameValueCollection ImageResizer.ExtensionMethods.NameValueCollectionExtensions.Set< T > (NameValueCollection q, string name, T? val) [inline, static]
Provides culture-invariant serialization of value types, in lower case for querystring readability. Setting a key to null removes it.
Template Parameters:
T
Parameters:
q
name
val
Returns:
Type Constraints
T : struct
T : IConvertible
Definition at line 131 of file NameValueCollection.cs.
                                                                                                     : struct, IConvertible {
            if (val == null) q.Remove(name);
            else q[name] = SerializePrimitive<T>(val);
            return q;
        }
static NameValueCollection ImageResizer.ExtensionMethods.NameValueCollectionExtensions.SetAsString< T > (NameValueCollection q, string name, T val) [inline, static]
Serializes the given value by calling .ToString(). If the value is null, the key is removed.
Template Parameters:
T
Parameters:
q
name
val
Returns:
Type Constraints
T : class
Definition at line 117 of file NameValueCollection.cs.
                                                                                                            : class {
            if (val == null) q.Remove(name);
            else q[name] = val.ToString();
            return q;
        }
The documentation for this class was generated from the following file:
C:/Users/Administrator/Documents/resizer/Core/ExtensionMethods/NameValueCollection.cs