ImageResizer: ImageResizer.Util.PathUtils Class Reference
ImageResizer.Util.PathUtils Class Reference
A set of utility methods for manipulating virtual paths.
Public Member Functions
delegate string VariableResolverCallback (string variableName)
A method that resolves variable names to values for the ResolveVariablesInPath method.
Static Public Member Functions
static string SetExtension (string path, string newExtension)
Should be called SetFullExtension. Sets the file extension of the specified path to the specified value, returning the result. If an extension has multiple parts, it will replace all of them. Leading dots will be stripped from 'newExtension' and re-addd as required. The querystring and fragment is maintained as-is. Semicolon syntax not supported.
static string RemoveFullExtension (string path)
Removes all extension segments from the filename or URL, leaving the querystring intact. I.e, image.jpg.bmp.tiff?hi would be image?hi The querystring and fragment is maintained as-is. Semicolon syntax not supported.
static string RemoveExtension (string path)
Removes the extension from the filename or URL, leaving the querystring intact, where the extension is only the last extension segment. I.e, image.jpg.bmp.tiff?hi would be image.jpg.bmp?hi after this call. The querystring and fragment is maintained as-is. Semicolon syntax not supported.
static string AddExtension (string path, string newExtension)
Adds the specified extension to path, returning the result. Multiple calls will result in "path.ext.ext.ext.ext". The querystring and fragment is maintained as-is. Semicolon syntax not supported.
static string GetFullExtension (string path)
Will return the full extension, like ".jpg.ashx", not just the last bit. Excludes extensions containing spaces or slashes. The querystring and fragment is ignored. Semicolon syntax not supported.
static string GetExtension (string path)
Grabs the last segment of the filename extension. Returns an empty string if there is no extension, or if the extension contains a space. Includes the leading '.' The querystring and fragment is ignored. Semicolon syntax not supported.
static string ResolveAppRelative (string virtualPath)
Resolves app-relative paths to virtual paths. Does nothing with virtual or relative paths.
static string ResolveAppRelativeAssumeAppRelative (string virtualPath)
Turns relative paths into domain-relative paths. Turns app-relative paths into domain relative paths.
static string AddQueryString (string virtualPath, string querystring)
Joins the path and querystring. If the path already contains a querystring, they are 'append joined' with the correct character. Fragment is maintained as-is. Does not support the semicolon syntax.
static string RemoveQueryString (string path)
Removes the query string from the specifed path. If the path is only a querystring, an empty string is returned. Does not support the semicolon syntax. Fragment is maintained as-is.
static string MergeOverwriteQueryString (string path, NameValueCollection newQuerystring)
Overwrites exisisting querystring values in 'path' with the values in 'newQuerystring'. Does not support the semicolon syntax.
static string MergeQueryString (string path, NameValueCollection newQuerystring)
Adds the querystring values in 'newQuerystring' to the querystring in Path, but does not overwrite values. Does not support the semicolon syntax.
static string BuildQueryString (NameValueCollection QueryString)
Returns a string querystring in the form "?key=value&amp;key=value". Keys and values are UrlEncoded as they should be.
static string BuildQueryString (NameValueCollection QueryString, bool urlEncode)
Returns a string querystring in the form "?key=value&amp;key=value". Keys and values are UrlEncoded if urlEncode=true.
static string BuildSemicolonQueryString (NameValueCollection QueryString, bool urlEncode)
Returns a string querystring in the form ";key=value;key=value". Keys and values are UrlEncoded if urlEncode=true.
static string BuildQueryString (NameValueCollection QueryString, bool urlEncode, bool skipNullValues=true, char firstSeparator= '?', char laterSeparators= '&', char equals= '=')
Build a customized querystring from a NameValueCollection.
static NameValueCollection ParseQueryStringFriendly (string path)
Like ParseQueryString, but permits the leading '?' to be omitted. Does not support the semicolon syntax.
static NameValueCollection ParseQueryStringFriendlyAllowSemicolons (string path)
Like ParseQueryString, but permits the leading '?' to be omitted, and semicolons can be substituted for '&'.
static NameValueCollection ParseQueryString (string path)
Parses the querystring from the given path into a NameValueCollection. accepts "file?key=value" and "?key=value&amp;key2=value2" formats. (no path is required) UrlDecodes keys and values.
static NameValueCollection ParseQueryString (string path, bool allowSemicolons)
Parses the querystring from the given path into a NameValueCollection. accepts "file?key=value" and "?key=value&amp;key2=value2" formats. (no path is required) UrlDecodes keys and values. Does not enforce correct syntax, I.E. '?key=value?key2=value2' is allowed. However, '&key=value?key2=value' will only get key2 parsed. When allowSemicolons is true, semicolon paths like ';key=value;key2=value2' are allowed, as are hybrid paths: ';key=value?key2=value2&key3=value3'.
static NameValueCollection ParseQueryString (string path, bool allowSemicolons, out string beforeQuery, out string fragment)
Parses the querystring from the given path into a NameValueCollection. accepts "file?key=value" and "?key=value&amp;key2=value2" formats. (no path is required) UrlDecodes keys and values. Does not enforce correct syntax, I.E. '?key=value?key2=value2' is allowed. However, '&key=value?key2=value' will only get key2 parsed. When allowSemicolons is true, semicolon paths like ';key=value;key2=value2' are allowed, as are hybrid paths: ';key=value?key2=value2&key3=value3'.
static NameValueCollection ParseQueryOnly (string query, bool allowSemicolons=true, bool urlDecode=true)
Parses a querystring into a name/value collection. The given string cannot include path or fragment information - it must be *just* the querystring.
static string ToBase64U (byte[] data)
Converts aribtrary bytes to a URL-safe version of base64 (no = padding, with - instead of + and _ instead of /)
static byte[] FromBase64UToBytes (string data)
Converts a URL-safe version of base64 to a byte array. (no = padding, with - instead of + and _ instead of /)
static string ToBase64U (string data)
Converts aribtrary strings to a URL-safe version of base64 (no = padding, with - instead of + and _ instead of /)
static string FromBase64UToString (string data)
Converts a URL-safe version of base64 to a string. 64U is (no = padding, with - instead of + and _ instead of /)
static string MapPathIfAppRelative (string path)
Returns the physcial mapped path for the specified virtual path if it starts with ~, otherwise retuns the original path.
static string GenerateImageUrl (string path, NameValueCollection query)
Generates a resized image url for the specified physical or virtual path. Not CloudFront compatible. Does not support remote URLs, use RemoteReader for that. If you're running in IIS classic, add ".ashx" to the 'path' parameter.
static string GuessVirtualPath (string path)
Attempts to guess the virtual path from physical path. Will be thrwarted if the path is mapped as a virtual folder inside the application. If the path is a non-physical path, it will be returned as is. Returns null if the physical path isn't a subfolder of the application's physical path.
static string ResolveVariablesInPath (string pathWithVars, VariableResolverCallback resolver)
Replaces variables in paths with their values. Ex. ~/uploads/thumbs/<guid>.<ext>. Standard variables are <ext> (the default extension for the final file type), <guid>, a randomly generated GUID, <filename>, the original filename without it's extension, <path>, the original path and filename without extension, <settings.width>, (any specified settings value except preset), <width> (final width), and <height> (final height).
static string RemoveNonMatchingChars (string text, string chars)
Allows a string to be filtered using the specified whitelisting expression (regex style).
static NameValueCollection FilterQueryString (ResizeSettings query, params string[] keepKeys)
Returns a new collection containing only the specified keys from the old one.
Properties
static string AppVirtualPath [get]
Returns HostingEnvironment.ApplicationVirtualPath or "/", if asp.net is not running.
static string AppPhysicalPath [get]
If not running in ASP.NET, returns the folder containing the DLL.
Detailed Description
A set of utility methods for manipulating virtual paths.
Definition at line 17 of file PathUtils.cs.
Member Function Documentation
static string ImageResizer.Util.PathUtils.AddExtension (string path, string newExtension) [inline, static]
Adds the specified extension to path, returning the result. Multiple calls will result in "path.ext.ext.ext.ext". The querystring and fragment is maintained as-is. Semicolon syntax not supported.
Parameters:
path
newExtension
Returns:
Definition at line 104 of file PathUtils.cs.
{
            int query = path.IndexOfAny(QueryOrFragment);
            if (query < 0) query = path.Length;
            return path.Substring(0, query) + "." + newExtension.TrimStart('.') + path.Substring(query);
        }
static string ImageResizer.Util.PathUtils.AddQueryString (string virtualPath, string querystring) [inline, static]
Joins the path and querystring. If the path already contains a querystring, they are 'append joined' with the correct character. Fragment is maintained as-is. Does not support the semicolon syntax.
Parameters:
virtualPath
querystring
Returns:
Definition at line 178 of file PathUtils.cs.
{
            //Separate the fragment if it's present, and restore it later
            int fragment = virtualPath.IndexOf('#');
            string suffix = "";
            if (fragment < 0) fragment = virtualPath.Length;
            else {
                suffix = virtualPath.Substring(fragment);
                virtualPath = virtualPath.Substring(0, fragment);
            }
            if (virtualPath.IndexOf('?') > -1) virtualPath = virtualPath.TrimEnd('&') + '&';
            else virtualPath += '?';
            return virtualPath + querystring.TrimStart('&', '?') + suffix;
        }
static string ImageResizer.Util.PathUtils.BuildQueryString (NameValueCollection QueryString) [inline, static]
Returns a string querystring in the form "?key=value&amp;key=value". Keys and values are UrlEncoded as they should be.
Parameters:
QueryString
Returns:
Definition at line 249 of file PathUtils.cs.
Referenced by ImageResizer.Plugins.RemoteReader.RemoteReaderPlugin.CreateSignedUrl(), ImageResizer.Mvc.ImageRequestAction.ExecuteVirtualFileResult(), ImageResizer.InterceptModule.HandleRequest(), ImageResizer.Instructions.ToQueryString(), ImageResizer.ResizeSettings.ToString(), and ImageResizer.ResizeSettings.ToStringEncoded().
{
            return BuildQueryString(QueryString, true);
        }
static string ImageResizer.Util.PathUtils.BuildQueryString (NameValueCollection QueryString, bool urlEncode) [inline, static]
Returns a string querystring in the form "?key=value&amp;key=value". Keys and values are UrlEncoded if urlEncode=true.
Parameters:
QueryString
urlEncode
Returns:
Definition at line 259 of file PathUtils.cs.
{
            return BuildQueryString(QueryString, urlEncode, true, '?', '&', '=');
        }
static string ImageResizer.Util.PathUtils.BuildQueryString (NameValueCollection QueryString, bool urlEncode, bool skipNullValues = true, char firstSeparator = '?', char laterSeparators = '&', char equals = '=') [inline, static]
Build a customized querystring from a NameValueCollection.
Parameters:
QueryString
urlEncode True to URL encode all values
skipNullValues If true, null-valued keys will be skipped
firstSeparator Usually ? or ;
laterSeparators Usually & or ;
equals Always =
Returns:
Definition at line 284 of file PathUtils.cs.
{
            if (QueryString.Count < 1) return ""; //No keys? return empty string.
            StringBuilder path = new StringBuilder();
            path.Append(firstSeparator);
            foreach (string key in QueryString.Keys) {
                if (key == null) continue; //Skip null keys
                string value = QueryString[key];
                if (skipNullValues && value == null) continue; //Optionally skip null values
                path.Append(urlEncode ? HttpUtility.UrlEncode(key) : key);
                path.Append(equals);
                path.Append(urlEncode ? HttpUtility.UrlEncode(value) : value);
                path.Append(laterSeparators);
            }
            if (path[path.Length - 1] == laterSeparators) path.Remove(path.Length - 1, 1);
            return path.ToString();
        }
static string ImageResizer.Util.PathUtils.BuildSemicolonQueryString (NameValueCollection QueryString, bool urlEncode) [inline, static]
Returns a string querystring in the form ";key=value;key=value". Keys and values are UrlEncoded if urlEncode=true.
Parameters:
QueryString
urlEncode
Returns:
Definition at line 271 of file PathUtils.cs.
Referenced by ImageResizer.Instructions.ToString().
{
            return BuildQueryString(QueryString, urlEncode, true, ';', ';', '=');
        }
static NameValueCollection ImageResizer.Util.PathUtils.FilterQueryString (ResizeSettings query, params string[] keepKeys) [inline, static]
Returns a new collection containing only the specified keys from the old one.
Parameters:
query
keepKeys
Returns:
Definition at line 583 of file PathUtils.cs.
{
            return NameValueCollectionExtensions.Keep(query, keepKeys);
        }
static byte [] ImageResizer.Util.PathUtils.FromBase64UToBytes (string data) [inline, static]
Converts a URL-safe version of base64 to a byte array. (no = padding, with - instead of + and _ instead of /)
Parameters:
data
Returns:
Definition at line 445 of file PathUtils.cs.
Referenced by ImageResizer.Plugins.SeamCarving.SeamCarvingPlugin.LayoutImage().
{
            data = data.PadRight(data.Length + ((4 - data.Length % 4) % 4), '='); //if there is 1 leftover octet, add ==, if 2, add =. 3 octects = 4 chars.
            return Convert.FromBase64String(data.Replace('-', '+').Replace('_', '/'));
        }
static string ImageResizer.Util.PathUtils.FromBase64UToString (string data) [inline, static]
Converts a URL-safe version of base64 to a string. 64U is (no = padding, with - instead of + and _ instead of /)
Parameters:
data
Returns:
Definition at line 462 of file PathUtils.cs.
Referenced by ImageResizer.Plugins.RemoteReader.RemoteReaderPlugin.ParseRequest().
{
            return UTF8Encoding.UTF8.GetString(FromBase64UToBytes(data));
        }
static string ImageResizer.Util.PathUtils.GenerateImageUrl (string path, NameValueCollection query) [inline, static]
Generates a resized image url for the specified physical or virtual path. Not CloudFront compatible. Does not support remote URLs, use RemoteReader for that. If you're running in IIS classic, add ".ashx" to the 'path' parameter.
Parameters:
path
query
Returns:
Definition at line 483 of file PathUtils.cs.
{
            return ResolveAppRelative(GuessVirtualPath(path)) + BuildQueryString(query);
        }
static string ImageResizer.Util.PathUtils.GetExtension (string path) [inline, static]
Grabs the last segment of the filename extension. Returns an empty string if there is no extension, or if the extension contains a space. Includes the leading '.' The querystring and fragment is ignored. Semicolon syntax not supported.
Parameters:
path
Returns:
Definition at line 134 of file PathUtils.cs.
Referenced by ImageResizer.ImageJob.ResolveTemplatedPath().
{
            int query = path.IndexOfAny(QueryOrFragment);
            if (query < 0) query = path.Length;
            //Finds the first character that could possibly be part of the extension (before the query)
            int firstPossibleExtensionChar = path.LastIndexOfAny(SpaceOrSlash, query - 1) + 1;
            int extensionStarts = path.LastIndexOf('.', query -1, query - firstPossibleExtensionChar );
            if (extensionStarts < 0) extensionStarts = query;
            return path.Substring(extensionStarts, query - extensionStarts);
        }
static string ImageResizer.Util.PathUtils.GetFullExtension (string path) [inline, static]
Will return the full extension, like ".jpg.ashx", not just the last bit. Excludes extensions containing spaces or slashes. The querystring and fragment is ignored. Semicolon syntax not supported.
Parameters:
path
Returns:
Definition at line 116 of file PathUtils.cs.
Referenced by ImageResizer.Mvc.ImageRequestAction.ExecuteVirtualFileResult(), and ImageResizer.InterceptModule.HandleRequest().
{
            int query = path.IndexOfAny(QueryOrFragment);
            if (query < 0) query = path.Length;
            //Finds the first character that could possibly be part of the extension (before the query)
            int firstPossibleExtensionChar = path.LastIndexOfAny(SpaceOrSlash, query - 1) + 1;
            int extensionStarts = path.IndexOf('.', firstPossibleExtensionChar, query - firstPossibleExtensionChar);
            if (extensionStarts < 0) extensionStarts = query;
            return path.Substring(extensionStarts, query - extensionStarts);
        }
static string ImageResizer.Util.PathUtils.GuessVirtualPath (string path) [inline, static]
Attempts to guess the virtual path from physical path. Will be thrwarted if the path is mapped as a virtual folder inside the application. If the path is a non-physical path, it will be returned as is. Returns null if the physical path isn't a subfolder of the application's physical path.
Parameters:
path
Returns:
Definition at line 494 of file PathUtils.cs.
{
            //If there's no windows slashes, it's probably virtual.
            if (path.IndexOf('\\') < 0)
                return path;
            string appPath = HostingEnvironment.ApplicationPhysicalPath;
            //Otherwise, try to get the full path so we can compare it.
            if (!Path.IsPathRooted(path)) path = Path.Combine(appPath, path);
            path = Path.GetFullPath(path);
            //If it's a match, strip it and convert it to a virtual path.
            if (path.StartsWith(appPath, StringComparison.OrdinalIgnoreCase)) {
                //Convert to app-relative path missing the ~/
                path = path.Remove(0, appPath.Length).TrimStart(new char[] { '/', '\\', '~' }).Replace('\\', '/');
                return PathUtils.ResolveAppRelativeAssumeAppRelative(path);
            }
            return null;
        }
static string ImageResizer.Util.PathUtils.MapPathIfAppRelative (string path) [inline, static]
Returns the physcial mapped path for the specified virtual path if it starts with ~, otherwise retuns the original path.
Parameters:
path
Returns:
Definition at line 470 of file PathUtils.cs.
Referenced by ImageResizer.ImageJob.ResolveTemplatedPath().
{
            return (path.StartsWith("~", StringComparison.OrdinalIgnoreCase)) ? HostingEnvironment.MapPath(path) : path;
        }
static string ImageResizer.Util.PathUtils.MergeOverwriteQueryString (string path, NameValueCollection newQuerystring) [inline, static]
Overwrites exisisting querystring values in 'path' with the values in 'newQuerystring'. Does not support the semicolon syntax.
Parameters:
path
newQuerystring
Returns:
Definition at line 220 of file PathUtils.cs.
{
            NameValueCollection oldQuery = ParseQueryString(path);
            //Overwrite old with new
            foreach (string key in newQuerystring.Keys)
                if (key != null) oldQuery[key] = newQuerystring[key];
            return AddQueryString(RemoveQueryString(path), BuildQueryString(oldQuery));
        }
static string ImageResizer.Util.PathUtils.MergeQueryString (string path, NameValueCollection newQuerystring) [inline, static]
Adds the querystring values in 'newQuerystring' to the querystring in Path, but does not overwrite values. Does not support the semicolon syntax.
Parameters:
path
newQuerystring
Returns:
Definition at line 234 of file PathUtils.cs.
{
            NameValueCollection oldQuery = ParseQueryString(path);
            //Overwrite new with old
            foreach (string key in oldQuery.Keys)
                if (key != null) newQuerystring[key] = oldQuery[key];
            return AddQueryString(RemoveQueryString(path), BuildQueryString(newQuerystring));
        }
static NameValueCollection ImageResizer.Util.PathUtils.ParseQueryOnly (string query, bool allowSemicolons = true, bool urlDecode = true) [inline, static]
Parses a querystring into a name/value collection. The given string cannot include path or fragment information - it must be *just* the querystring.
Parameters:
query
allowSemicolons
urlDecode
Returns:
Definition at line 408 of file PathUtils.cs.
{
            string[] pairs = query.Split(allowSemicolons ? new char[] { '?', '&', ';' } : new char[] { '?', '&' }, StringSplitOptions.RemoveEmptyEntries);
            NameValueCollection c = new NameValueCollection();
            foreach (string s in pairs) {
                string[] namevalue = s.Split(new char[] { '=' }, StringSplitOptions.RemoveEmptyEntries);
                if (namevalue.Length > 2) {
                    //Handle &key=value=value and &key===value=value -> key : "value=value"
                    string value = s.Substring(s.IndexOf('=')).TrimStart('=');
                    c[urlDecode ? HttpUtility.UrlDecode(namevalue[0]) : namevalue[0]] =
                        urlDecode ? HttpUtility.UrlDecode(value) : value;
                } else if (namevalue.Length == 2) {
                    //Handle key=value (normal)
                    c[urlDecode ? HttpUtility.UrlDecode(namevalue[0]) : namevalue[0]] =
                        urlDecode ? HttpUtility.UrlDecode(namevalue[1]) : namevalue[1];
                } else if (namevalue.Length == 1){
                    //Hanlde &key=&key2= or &key&key2 -> key: "", key2: ""
                    //Setting a null value would be confusing, as that is how we determine
                    //whether a certain paramater exists
                    c[urlDecode ? HttpUtility.UrlDecode(namevalue[0]) : namevalue[0]] = "";
                }
            }
            return c;
        }
static NameValueCollection ImageResizer.Util.PathUtils.ParseQueryString (string path) [inline, static]
Parses the querystring from the given path into a NameValueCollection. accepts "file?key=value" and "?key=value&amp;key2=value2" formats. (no path is required) UrlDecodes keys and values.
Parameters:
path
Returns:
Definition at line 344 of file PathUtils.cs.
{
            return ParseQueryString(path, false);
        }
static NameValueCollection ImageResizer.Util.PathUtils.ParseQueryString (string path, bool allowSemicolons) [inline, static]
Parses the querystring from the given path into a NameValueCollection. accepts "file?key=value" and "?key=value&amp;key2=value2" formats. (no path is required) UrlDecodes keys and values. Does not enforce correct syntax, I.E. '?key=value?key2=value2' is allowed. However, '&key=value?key2=value' will only get key2 parsed. When allowSemicolons is true, semicolon paths like ';key=value;key2=value2' are allowed, as are hybrid paths: ';key=value?key2=value2&key3=value3'.
Parameters:
path
allowSemicolons
Returns:
Definition at line 357 of file PathUtils.cs.
{
            string s, f;
            return ParseQueryString(path, allowSemicolons, out s,out f);
        }
static NameValueCollection ImageResizer.Util.PathUtils.ParseQueryString (string path, bool allowSemicolons, out string beforeQuery, out string fragment) [inline, static]
Parses the querystring from the given path into a NameValueCollection. accepts "file?key=value" and "?key=value&amp;key2=value2" formats. (no path is required) UrlDecodes keys and values. Does not enforce correct syntax, I.E. '?key=value?key2=value2' is allowed. However, '&key=value?key2=value' will only get key2 parsed. When allowSemicolons is true, semicolon paths like ';key=value;key2=value2' are allowed, as are hybrid paths: ';key=value?key2=value2&key3=value3'.
Does NOT parse fragments correctly.
Parameters:
path
allowSemicolons
beforeQuery Returns the portion of the 'path' before the querystring. May include the scheme, server, port, path and path info, depending upon what 'path' contained.
Returns:
Definition at line 374 of file PathUtils.cs.
{
            //Separate the fragment if it's present, and restore it later
            int frag = path.IndexOf('#');
            if (frag < 0) fragment = "";
            else {
                fragment = path.Substring(frag);
                path = path.Substring(0, frag);
            }
            int firstdelimiter = path.IndexOf('?');
            if (allowSemicolons) {
                //Use the index if whichever is first, and preset
                int firstsemicolon = path.IndexOf(';');
                if (firstdelimiter < 0 || (firstsemicolon >= 0 && firstsemicolon < firstdelimiter)) firstdelimiter = firstsemicolon;
            }
            if (firstdelimiter < 0 || firstdelimiter >= path.Length) {
                //No query string detected
                beforeQuery = path;
                return new NameValueCollection();
            } else {
                beforeQuery = path.Substring(0, firstdelimiter);
            }
            return ParseQueryOnly(path.Substring(firstdelimiter, path.Length - firstdelimiter),allowSemicolons);
        }
static NameValueCollection ImageResizer.Util.PathUtils.ParseQueryStringFriendly (string path) [inline, static]
Like ParseQueryString, but permits the leading '?' to be omitted. Does not support the semicolon syntax.
Parameters:
path
Returns:
Definition at line 312 of file PathUtils.cs.
{
            if (path.IndexOf('?') < 0 && path.IndexOf('=') >= 0) path = '?' + path;
            return ParseQueryString(path,false);
        }
static NameValueCollection ImageResizer.Util.PathUtils.ParseQueryStringFriendlyAllowSemicolons (string path) [inline, static]
Like ParseQueryString, but permits the leading '?' to be omitted, and semicolons can be substituted for '&'.
Parameters:
path
Returns:
Definition at line 322 of file PathUtils.cs.
{
            //Delete the fragment before we start
            int fragment = path.IndexOf('#');
            if (fragment > -1) path = path.Substring(0, fragment);
            int eq = path.IndexOf('=');
            int quest = path.IndexOf('?');
            int semi = path.IndexOf(';');
            if (eq >= 0 && //We have equals, which indicates a query
                quest < 0 && //But no question mark!
                (eq < semi || semi < 0)) //An no semicolon, or else a semicolon *after* the first equals.
                path = '?' + path;
            return ParseQueryString(path,true);
        }
static string ImageResizer.Util.PathUtils.RemoveExtension (string path) [inline, static]
Removes the extension from the filename or URL, leaving the querystring intact, where the extension is only the last extension segment. I.e, image.jpg.bmp.tiff?hi would be image.jpg.bmp?hi after this call. The querystring and fragment is maintained as-is. Semicolon syntax not supported.
Parameters:
path
Returns:
Definition at line 85 of file PathUtils.cs.
Referenced by ImageResizer.ImageJob.ResolveTemplatedPath().
{
            int query = path.IndexOfAny(QueryOrFragment);
            if (query < 0) query = path.Length;
            //Finds the first character that could possibly be part of the extension (before the query)
            int firstPossibleExtensionChar = path.LastIndexOfAny(SpaceOrSlash, query - 1) + 1;
            int extensionStarts = path.LastIndexOf('.', query - 1, query - firstPossibleExtensionChar);
            if (extensionStarts < 0) extensionStarts = query;
            return path.Substring(0, extensionStarts) + path.Substring(query);
        }
static string ImageResizer.Util.PathUtils.RemoveFullExtension (string path) [inline, static]
Removes all extension segments from the filename or URL, leaving the querystring intact. I.e, image.jpg.bmp.tiff?hi would be image?hi The querystring and fragment is maintained as-is. Semicolon syntax not supported.
Parameters:
path
Returns:
Definition at line 66 of file PathUtils.cs.
Referenced by ImageResizer.Plugins.MongoReader.MongoReaderPlugin.MongoVirtualFile.Open().
{
            int query = path.IndexOfAny(QueryOrFragment);
            if (query < 0) query = path.Length;
            //Finds the first character that could possibly be part of the extension (before the query)
            int firstPossibleExtensionChar = path.LastIndexOfAny(SpaceOrSlash, query - 1) + 1;
            int extensionStarts = path.IndexOf('.', firstPossibleExtensionChar, query - firstPossibleExtensionChar);
            if (extensionStarts < 0) extensionStarts = query;
            return path.Substring(0, extensionStarts) + path.Substring(query);
        }
static string ImageResizer.Util.PathUtils.RemoveNonMatchingChars (string text, string chars) [inline, static]
Allows a string to be filtered using the specified whitelisting expression (regex style).
I.e, "hi YOU 3", "a-z3" will produce "hi3".
Parameters:
text
chars
Returns:
Definition at line 560 of file PathUtils.cs.
{
            StringBuilder sb = new StringBuilder();
            Regex r = new Regex("[" + Regex.Escape(chars) + "]", RegexOptions.Compiled);
            for (int i = 0; i < text.Length; i++) {
                string chr = text.Substring(i,1);
                if (r.IsMatch(chr)) sb.Append(chr);
            }
            return sb.ToString();
        }
static string ImageResizer.Util.PathUtils.RemoveQueryString (string path) [inline, static]
Removes the query string from the specifed path. If the path is only a querystring, an empty string is returned. Does not support the semicolon syntax. Fragment is maintained as-is.
Parameters:
path
Returns:
Definition at line 199 of file PathUtils.cs.
{
            //Separate the fragment if it's present, and restore it later
            int fragment = path.IndexOf('#');
            string suffix = "";
            if (fragment < 0) fragment = path.Length;
            else {
                suffix = path.Substring(fragment);
                path = path.Substring(0, fragment);
            }
            int delimiter = path.IndexOf('?');
            return delimiter > -1 ? path.Substring(0, delimiter) + suffix : path;
        }
static string ImageResizer.Util.PathUtils.ResolveAppRelative (string virtualPath) [inline, static]
Resolves app-relative paths to virtual paths. Does nothing with virtual or relative paths.
Parameters:
virtualPath
Returns:
Definition at line 150 of file PathUtils.cs.
Referenced by ImageResizer.ImageBuilder.GetStreamFromSource().
{
            //resolve tilde
            if (virtualPath.StartsWith("~", StringComparison.OrdinalIgnoreCase)) return HostingEnvironment.ApplicationVirtualPath.TrimEnd('/') + '/' + virtualPath.TrimStart('~', '/');
            return virtualPath;
        }
static string ImageResizer.Util.PathUtils.ResolveAppRelativeAssumeAppRelative (string virtualPath) [inline, static]
Turns relative paths into domain-relative paths. Turns app-relative paths into domain relative paths.
Parameters:
virtualPath
Returns:
Definition at line 162 of file PathUtils.cs.
Referenced by ImageResizer.InterceptModule.CheckRequest_PostAuthorizeRequest(), ImageResizer.Mvc.ImageRequestAction.ExecuteVirtualPathResult(), and ImageResizer.Util.PathUtils.GuessVirtualPath().
{
            if (virtualPath.StartsWith("~")) return HostingEnvironment.ApplicationVirtualPath.TrimEnd('/') + "/" + virtualPath.TrimStart('~', '/');
            if (!virtualPath.StartsWith("/")) return HostingEnvironment.ApplicationVirtualPath.TrimEnd('/') + "/" + virtualPath;
            return virtualPath;
        }
static string ImageResizer.Util.PathUtils.ResolveVariablesInPath (string pathWithVars, VariableResolverCallback resolver) [inline, static]
Replaces variables in paths with their values. Ex. ~/uploads/thumbs/<guid>.<ext>. Standard variables are <ext> (the default extension for the final file type), <guid>, a randomly generated GUID, <filename>, the original filename without it's extension, <path>, the original path and filename without extension, <settings.width>, (any specified settings value except preset), <width> (final width), and <height> (final height).
Parameters:
pathWithVars
resolver
Returns:
Definition at line 524 of file PathUtils.cs.
Referenced by ImageResizer.ImageJob.ResolveTemplatedPath().
{
            string p = pathWithVars;
            while (p.IndexOf('<') > -1) {
                int start = p.IndexOf('<');
                int stop = p.IndexOf('>',start);
                int bugcheck = p.IndexOf('<',start + 1);
                if (stop < 0 || (bugcheck > -1 && bugcheck < stop) || stop == start + 1)
                    throw new ImageProcessingException("Destination paths can only contain < and > in matched pairs to designate variables. Path \"" + pathWithVars + "\" has invalid syntax");
                string varName = p.Substring(start + 1,stop - start -1);
                string filter = null;
                //Split off the filter if present.
                int filterIx = varName.IndexOf(':');
                if (filterIx > 0) {
                    filter = varName.Substring(filterIx + 1);
                    varName = varName.Substring(0, filterIx);
                }
                varName = varName.ToLowerInvariant();
                string result = resolver(varName);
                if (!string.IsNullOrEmpty(filter)) {
                    result = RemoveNonMatchingChars(result, filter);
                }
                if (result == null)
                    throw new ImageProcessingException("Invalid variable name \"" + varName + "\" in templated path \"" + pathWithVars + "\". The variable name may be mispelled, or the variable may not be available with the pipeline you are using.");
                p = p.Substring(0,start) + result + p.Substring(stop + 1);
            }
            if (p.IndexOf('>') > -1) throw new ImageProcessingException("Orphaned '>' in template path \"" + pathWithVars + "\".");
            return p;
        }
static string ImageResizer.Util.PathUtils.SetExtension (string path, string newExtension) [inline, static]
Should be called SetFullExtension. Sets the file extension of the specified path to the specified value, returning the result. If an extension has multiple parts, it will replace all of them. Leading dots will be stripped from 'newExtension' and re-addd as required. The querystring and fragment is maintained as-is. Semicolon syntax not supported.
Parameters:
path
newExtension
Returns:
Definition at line 48 of file PathUtils.cs.
{
            int query = path.IndexOfAny(QueryOrFragment);
            if (query < 0) query = path.Length;
            //Finds the first character that could possibly be part of the extension (before the query)
            int firstPossibleExtensionChar = path.LastIndexOfAny(SpaceOrSlash, query - 1) + 1;
            int extensionStarts = path.IndexOf('.', firstPossibleExtensionChar, query - firstPossibleExtensionChar);
            if (extensionStarts < 0) extensionStarts = query;
            return path.Substring(0, extensionStarts) + (!string.IsNullOrEmpty(newExtension) ? "." + newExtension.TrimStart('.') : "") + path.Substring(query);
        }
static string ImageResizer.Util.PathUtils.ToBase64U (byte[] data) [inline, static]
Converts aribtrary bytes to a URL-safe version of base64 (no = padding, with - instead of + and _ instead of /)
Parameters:
data
Returns:
Definition at line 437 of file PathUtils.cs.
Referenced by ImageResizer.Plugins.RemoteReader.RemoteReaderPlugin.CreateSignedUrl().
{
            return Convert.ToBase64String(data).Replace("=", String.Empty).Replace('+', '-').Replace('/', '_');
        }
static string ImageResizer.Util.PathUtils.ToBase64U (string data) [inline, static]
Converts aribtrary strings to a URL-safe version of base64 (no = padding, with - instead of + and _ instead of /)
Parameters:
data
Returns:
Definition at line 454 of file PathUtils.cs.
{
            return ToBase64U(UTF8Encoding.UTF8.GetBytes(data));
        }
delegate string ImageResizer.Util.PathUtils.VariableResolverCallback (string variableName)
A method that resolves variable names to values for the ResolveVariablesInPath method.
Parameters:
variableName
Returns:
Property Documentation
string ImageResizer.Util.PathUtils.AppPhysicalPath [static, get]
If not running in ASP.NET, returns the folder containing the DLL.
Definition at line 30 of file PathUtils.cs.
string ImageResizer.Util.PathUtils.AppVirtualPath [static, get]
Returns HostingEnvironment.ApplicationVirtualPath or "/", if asp.net is not running.
Definition at line 22 of file PathUtils.cs.
The documentation for this class was generated from the following file:
C:/Users/Administrator/Documents/resizer/Core/Util/PathUtils.cs