ImageResizer: ImageResizer.Resizing.AbstractImageProcessor Class Reference
ImageResizer.Resizing.AbstractImageProcessor Class Reference
Not for external use. Inherit from BuilderExtension instead. Dual-purpose base class for both ImageBuilder and BuilderExtension Extensions can inherit and override certain methods. ImageBuilder inherits this method to utilize its extension invocation code. Each method of AbstractImageProcessor loops through all extensions and executes the same method on each. Provides a sort of multiple-inheritance mechanisim.
Public Member Functions
AbstractImageProcessor ()
Creates a new AbstractImageProcessor with no extensions.
AbstractImageProcessor (IEnumerable< BuilderExtension > extensions)
Creates a new AbstractImageProcessor which will run the specified extensions with each method call.
virtual Bitmap DecodeStreamFailed (Stream s, ResizeSettings settings, string optionalPath)
Extensions are executed until one extension returns a non-null value. This is taken to mean that the error has been resolved. Extensions should not throw an exception unless they wish to cause subsequent extensions to not execute. If extensions throw an ArgumentException or ExternalException, it will be wrapped in an ImageCorruptedException instance. If the Bitmap class is used for decoding, read gdi-bugs.txt and make sure you set b.Tag to new BitmapTag(optionalPath,stream);.
virtual Bitmap DecodeStream (Stream s, ResizeSettings settings, string optionalPath)
Extend this to support alternate image source formats. If the Bitmap class is used for decoding, read gdi-bugs.txt and make sure you set b.Tag to new BitmapTag(optionalPath,stream);.
Protected Member Functions
virtual void PreLoadImage (ref object source, ref string path, ref bool disposeSource, ref ResizeSettings settings)
Extend this to allow additional types of source objects to be accepted by transforming them into Bitmap instances.
virtual Stream GetStream (object source, ResizeSettings settings, ref bool disposeStream, out string path, out bool restoreStreamPosition)
Extend this to allow additional types of source objects to be accepted by transforming them into Stream instances. First plugin to return a Stream wins.
virtual RequestedAction PostDecodeStream (ref Bitmap img, ResizeSettings settings)
Extend this to modify the Bitmap instance after it has been decoded by DecodeStream or DecodeStreamFailed.
virtual void PreAcquireStream (ref object dest, ResizeSettings settings)
Extend this to allow additional types of *destination* objects to be accepted by transforming them into a stream.
virtual RequestedAction BuildJob (ImageResizer.ImageJob job)
The method to override if you want to replace the entire pipeline. All Build() calls call this method first. Does nothing in ImageBuilder.
virtual RequestedAction buildToStream (Bitmap source, Stream dest, ResizeSettings settings)
Called for Build() calls that want the result encoded. (Not for Bitmap Build(source,settings) calls. Only override this method if you need to replace the behavior of image encoding and image processing together, such as adding support for resizing multi-page TIFF files or animated GIFs.
virtual Bitmap buildToBitmap (Bitmap source, ResizeSettings settings, bool transparencySupported)
Most calls funnel through here. Default behavior configures an ImageState instance and calls Process(imageState); Shouldn't be overriden for any reason I can think of - use the appropriate virtual method under Process(). If an extension returns a Bitmap instance, it will be used instead of the default behavior. Does NOT dispose of 'source' or 'source's underlying stream.
virtual RequestedAction OnProcess (ImageState s)
Process.0 First step of the Process() method. Can replace the entire Process method if RequestAction.Cancel is returned. Can be used to add points to translate (for image maps), and also to modify the settings.
virtual RequestedAction PrepareSourceBitmap (ImageState s)
Process.1 Switches the bitmap to the correct frame or page, and applies source flipping commands.
virtual RequestedAction PostPrepareSourceBitmap (ImageState s)
Process.2 Extend this to apply any pre-processing to the source bitmap that needs to occur before Layout begins.
virtual RequestedAction Layout (ImageState s)
Process.3(Layout).0: This is the last point at which points to translate should be added. Only return RequestedAction.Cancel if you wish to replace the entire Layout sequence logic.
virtual RequestedAction FlipExistingPoints (ImageState s)
Process.3(Layout).1: This is where the points in the layout are flipped the same way the source bitmap was flipped (unless their flags specify otherwise)
virtual RequestedAction LayoutImage (ImageState s)
Process.3(Layout).2: Rings 'image' and 'imageArea' are added to the layout.
virtual RequestedAction PostLayoutImage (ImageState s)
Process.3(Layout).3: Add rings here to insert them between the image area and the padding.
virtual RequestedAction LayoutPadding (ImageState s)
Process.3(Layout).4: Ring "padding" is added to the layout.
virtual RequestedAction PostLayoutPadding (ImageState s)
Process.3(Layout).5: Add rings here to insert them between the padding and the border.
virtual RequestedAction LayoutBorder (ImageState s)
Process.3(Layout).6: Ring "border" is added to the layout.
virtual RequestedAction PostLayoutBorder (ImageState s)
Process.3(Layout).7: Add rings here to insert them between the border and the effect rings.
virtual RequestedAction LayoutEffects (ImageState s)
Process.3(Layout).8: Effects such as 'shadow' are added here.
virtual RequestedAction PostLayoutEffects (ImageState s)
Process.3(Layout).9: Add rings here to insert them between the effects and the margin.
virtual RequestedAction LayoutMargin (ImageState s)
Process.3(Layout).10: Margins are added to the layout.
virtual RequestedAction PostLayoutMargin (ImageState s)
Process.3(Layout).11: Add rings here to insert them around the margin. Rings will be outermost.
virtual RequestedAction LayoutRotate (ImageState s)
Process.3(Layout).anytime: Occurs when the layout is rotated. May be called anytime during Layout()
virtual RequestedAction PostLayoutRotate (ImageState s)
Process.3(Layout).anytime: Occurs after the layout is rotated. May be called anytime during Layout()
virtual RequestedAction LayoutNormalize (ImageState s)
Process.3(Layout).anytime: Occurs when the layout is normalized to 0,0. May be called anytime during Layout()
virtual RequestedAction PostLayoutNormalize (ImageState s)
Process.3(Layout).anytime: Occurs after the layout is normalized. May be called anytime during Layout()
virtual RequestedAction LayoutRound (ImageState s)
Process.3(Layout).anytime: Occurs when the layout point values are rounded to integers. May be called anytime during Layout()
virtual RequestedAction PostLayoutRound (ImageState s)
Process.3(Layout).anytime: Occurs after the layout point values are rounded to integers. May be called anytime during Layout()
virtual RequestedAction EndLayout (ImageState s)
Process.3(Layout).12: Occurs once layout has finished. No more changes should occur to points or rings in the layout after this method. destSize is calculated here.
virtual RequestedAction PrepareDestinationBitmap (ImageState s)
Process.4: The destination bitmap is created and sized based destSize. A graphics object is initialized for rendering.
virtual RequestedAction Render (ImageState s)
Process.5(Render) Rendering. Do not return RequestedAction.Cancel unless you want to replace the entire rendering system.
virtual RequestedAction RenderBackground (ImageState s)
Process.5(Render).1 The background color is rendered.
virtual RequestedAction PostRenderBackground (ImageState s)
Process.5(Render).2 After the background color is rendered.
virtual RequestedAction RenderEffects (ImageState s)
Process.5(Render).3 Effects (such as a drop shadow or outer glow) are rendered.
virtual RequestedAction PostRenderEffects (ImageState s)
Process.5(Render).4 After outer effects are rendered.
virtual RequestedAction RenderPadding (ImageState s)
Process.5(Render).5 Image padding is drawn.
virtual RequestedAction PostRenderPadding (ImageState s)
Process.5(Render).6 After image padding is drawn.
virtual RequestedAction CreateImageAttribues (ImageState s)
Process.5(Render).7: An ImageAttributes instance is created if it doesn't already exist.
virtual RequestedAction PostCreateImageAttributes (ImageState s)
Process.5(Render).8: The ImageAttributes instance exists and can be modified or replaced.
virtual RequestedAction PreRenderImage (ImageState s)
Process.5(Render).9: Plugins have a chance to pre-process the source image before it gets rendered, and save it to s.preRenderBitmap.
virtual RequestedAction RenderImage (ImageState s)
Process.5(Render).10: The image is copied to the destination parallelogram specified by ring 'image'.
virtual RequestedAction PostRenderImage (ImageState s)
Process.5(Render).11: After the image is drawn.
virtual RequestedAction RenderBorder (ImageState s)
Process.5(Render).12: The border is rendered.
virtual RequestedAction PostRenderBorder (ImageState s)
Process.5(Render).13: After the border is drawn.
virtual RequestedAction PreRenderOverlays (ImageState s)
Process.5(Render).14: Any last-minute changes before watermarking or overlays are applied.
virtual RequestedAction RenderOverlays (ImageState s)
Process.5(Render).15: Watermarks can be rendered here. All image processing should be done.
virtual RequestedAction PreFlushChanges (ImageState s)
Process.5(Render).16: Called before changes are flushed and the graphics object is destroyed.
virtual RequestedAction FlushChanges (ImageState s)
Process.5(Render).17: Changes are flushed to the bitmap here and the graphics object is destroyed.
virtual RequestedAction PostFlushChanges (ImageState s)
Process.5(Render).18: Changes have been flushed to the bitmap, but the final bitmap has not been flipped yet.
virtual RequestedAction ProcessFinalBitmap (ImageState s)
Process.6: Non-rendering changes to the bitmap object occur here, such as flipping. The graphics object is unavailable.
virtual RequestedAction EndProcess (ImageState s)
Process.7: Layout and rendering are both complete.
Protected Attributes
volatile IEnumerable
< BuilderExtension > exts
Contains the set of extensions that are called for every method.
Detailed Description
Not for external use. Inherit from BuilderExtension instead. Dual-purpose base class for both ImageBuilder and BuilderExtension Extensions can inherit and override certain methods. ImageBuilder inherits this method to utilize its extension invocation code. Each method of AbstractImageProcessor loops through all extensions and executes the same method on each. Provides a sort of multiple-inheritance mechanisim.
Definition at line 31 of file AbstractImageProcessor.cs.
Constructor & Destructor Documentation
ImageResizer.Resizing.AbstractImageProcessor.AbstractImageProcessor () [inline]
Creates a new AbstractImageProcessor with no extensions.
Definition at line 35 of file AbstractImageProcessor.cs.
{
            exts = null;
        }
ImageResizer.Resizing.AbstractImageProcessor.AbstractImageProcessor (IEnumerable< BuilderExtension > extensions) [inline]
Creates a new AbstractImageProcessor which will run the specified extensions with each method call.
Parameters:
extensions
Definition at line 42 of file AbstractImageProcessor.cs.
{
            exts = new List<BuilderExtension>(extensions != null ? extensions : new BuilderExtension[] { });
        }
Member Function Documentation
virtual RequestedAction ImageResizer.Resizing.AbstractImageProcessor.BuildJob (ImageResizer.ImageJob job) [inline, protected, virtual]
The method to override if you want to replace the entire pipeline. All Build() calls call this method first. Does nothing in ImageBuilder.
Parameters:
job
Returns:
Definition at line 151 of file AbstractImageProcessor.cs.
Referenced by ImageResizer.Resizing.AbstractImageProcessor.BuildJob().
{
            if (exts != null)
                foreach (AbstractImageProcessor p in exts)
                    if (p.BuildJob(job) == RequestedAction.Cancel)
                        return RequestedAction.Cancel;
            return RequestedAction.None;
        }
virtual Bitmap ImageResizer.Resizing.AbstractImageProcessor.buildToBitmap (Bitmap source, ResizeSettings settings, bool transparencySupported) [inline, protected, virtual]
Most calls funnel through here. Default behavior configures an ImageState instance and calls Process(imageState); Shouldn't be overriden for any reason I can think of - use the appropriate virtual method under Process(). If an extension returns a Bitmap instance, it will be used instead of the default behavior. Does NOT dispose of 'source' or 'source's underlying stream.
Parameters:
source
settings
transparencySupported
Returns:
Reimplemented in ImageResizer.ImageBuilder.
Definition at line 188 of file AbstractImageProcessor.cs.
Referenced by ImageResizer.Resizing.AbstractImageProcessor.buildToBitmap().
{
            if (exts != null) {
                foreach (AbstractImageProcessor p in exts) {
                    Bitmap b = p.buildToBitmap(source, settings, transparencySupported);
                    if (b != null) return b;
                }
            }
            return null;
        }
virtual RequestedAction ImageResizer.Resizing.AbstractImageProcessor.buildToStream (Bitmap source, Stream dest, ResizeSettings settings) [inline, protected, virtual]
Called for Build() calls that want the result encoded. (Not for Bitmap Build(source,settings) calls. Only override this method if you need to replace the behavior of image encoding and image processing together, such as adding support for resizing multi-page TIFF files or animated GIFs.
Does NOT dispose of 'source' or 'source's underlying stream.
Parameters:
source
dest
settings
Returns:
Reimplemented in ImageResizer.ImageBuilder, and ImageResizer.Plugins.AnimatedGifs.AnimatedGifs.
Definition at line 171 of file AbstractImageProcessor.cs.
Referenced by ImageResizer.Resizing.AbstractImageProcessor.buildToStream().
{
            if (exts != null)
                foreach (AbstractImageProcessor p in exts)
                    if (p.buildToStream(source, dest, settings) == RequestedAction.Cancel)
                        return RequestedAction.Cancel;
            return RequestedAction.None;
        }
virtual RequestedAction ImageResizer.Resizing.AbstractImageProcessor.CreateImageAttribues (ImageState s) [inline, protected, virtual]
Process.5(Render).7: An ImageAttributes instance is created if it doesn't already exist.
Parameters:
s
Reimplemented in ImageResizer.ImageBuilder.
Definition at line 531 of file AbstractImageProcessor.cs.
Referenced by ImageResizer.Resizing.AbstractImageProcessor.CreateImageAttribues().
{
            if (exts != null)
                foreach (AbstractImageProcessor p in exts)
                    if (p.CreateImageAttribues(s) == RequestedAction.Cancel)
                        return RequestedAction.Cancel;
            return RequestedAction.None;
        }
virtual Bitmap ImageResizer.Resizing.AbstractImageProcessor.DecodeStream (Stream s, ResizeSettings settings, string optionalPath) [inline, virtual]
Extend this to support alternate image source formats. If the Bitmap class is used for decoding, read gdi-bugs.txt and make sure you set b.Tag to new BitmapTag(optionalPath,stream);.
Parameters:
s
settings
optionalPath
Returns:
Reimplemented in ImageResizer.ImageBuilder, ImageResizer.Plugins.PdfRenderer.PdfRendererPlugin, ImageResizer.Plugins.PsdReader.PsdReader, and ImageResizer.Plugins.WebPDecoder.WebPDecoderPlugin.
Definition at line 114 of file AbstractImageProcessor.cs.
Referenced by ImageResizer.Resizing.AbstractImageProcessor.DecodeStream().
{
            if (exts == null) return null;
            foreach (AbstractImageProcessor p in exts) {
                Bitmap b = p.DecodeStream(s,settings, optionalPath);
                if (b != null) return b;
            }
            return null;
        }
virtual Bitmap ImageResizer.Resizing.AbstractImageProcessor.DecodeStreamFailed (Stream s, ResizeSettings settings, string optionalPath) [inline, virtual]
Extensions are executed until one extension returns a non-null value. This is taken to mean that the error has been resolved. Extensions should not throw an exception unless they wish to cause subsequent extensions to not execute. If extensions throw an ArgumentException or ExternalException, it will be wrapped in an ImageCorruptedException instance. If the Bitmap class is used for decoding, read gdi-bugs.txt and make sure you set b.Tag to new BitmapTag(optionalPath,stream);.
Reimplemented in ImageResizer.Plugins.PsdReader.PsdReader, and ImageResizer.Plugins.WebPDecoder.WebPDecoderPlugin.
Definition at line 95 of file AbstractImageProcessor.cs.
Referenced by ImageResizer.Resizing.AbstractImageProcessor.DecodeStreamFailed().
{
            if (exts == null) return null;
            foreach (AbstractImageProcessor p in exts) {
                if (s.CanSeek && s.Position != 0)
                    s.Seek(0, SeekOrigin.Begin);
                Bitmap b = p.DecodeStreamFailed(s,settings, optionalPath);
                if (b != null) return b;
            }
            return null;
        }
virtual RequestedAction ImageResizer.Resizing.AbstractImageProcessor.EndLayout (ImageState s) [inline, protected, virtual]
Process.3(Layout).12: Occurs once layout has finished. No more changes should occur to points or rings in the layout after this method. destSize is calculated here.
Parameters:
s
Reimplemented in ImageResizer.ImageBuilder.
Definition at line 431 of file AbstractImageProcessor.cs.
Referenced by ImageResizer.Resizing.AbstractImageProcessor.EndLayout().
{
            if (exts != null)
                foreach (AbstractImageProcessor p in exts)
                    if (p.EndLayout(s) == RequestedAction.Cancel)
                        return RequestedAction.Cancel;
            return RequestedAction.None;
        }
virtual RequestedAction ImageResizer.Resizing.AbstractImageProcessor.EndProcess (ImageState s) [inline, protected, virtual]
Process.7: Layout and rendering are both complete.
Parameters:
s
Definition at line 682 of file AbstractImageProcessor.cs.
Referenced by ImageResizer.Resizing.AbstractImageProcessor.EndProcess().
{
            if (exts != null)
                foreach (AbstractImageProcessor p in exts)
                    if (p.EndProcess(s) == RequestedAction.Cancel)
                        return RequestedAction.Cancel;
            return RequestedAction.None;
        }
virtual RequestedAction ImageResizer.Resizing.AbstractImageProcessor.FlipExistingPoints (ImageState s) [inline, protected, virtual]
Process.3(Layout).1: This is where the points in the layout are flipped the same way the source bitmap was flipped (unless their flags specify otherwise)
Parameters:
s
Definition at line 239 of file AbstractImageProcessor.cs.
Referenced by ImageResizer.Resizing.AbstractImageProcessor.FlipExistingPoints().
{
            if (exts != null) foreach (AbstractImageProcessor p in exts) if (p.FlipExistingPoints(s) == RequestedAction.Cancel) return RequestedAction.Cancel;
            return RequestedAction.None;
        }
virtual RequestedAction ImageResizer.Resizing.AbstractImageProcessor.FlushChanges (ImageState s) [inline, protected, virtual]
Process.5(Render).17: Changes are flushed to the bitmap here and the graphics object is destroyed.
Parameters:
s
Reimplemented in ImageResizer.ImageBuilder.
Definition at line 646 of file AbstractImageProcessor.cs.
Referenced by ImageResizer.Resizing.AbstractImageProcessor.FlushChanges().
{
            if (exts != null)
                foreach (AbstractImageProcessor p in exts)
                    if (p.FlushChanges(s) == RequestedAction.Cancel)
                        return RequestedAction.Cancel;
            return RequestedAction.None;
        }
virtual Stream ImageResizer.Resizing.AbstractImageProcessor.GetStream (object source, ResizeSettings settings, ref bool disposeStream, out string path, out bool restoreStreamPosition) [inline, protected, virtual]
Extend this to allow additional types of source objects to be accepted by transforming them into Stream instances. First plugin to return a Stream wins.
Parameters:
source
settings
disposeStream
path
restoreStreamPosition
Returns:
Reimplemented in ImageResizer.Plugins.RemoteReader.RemoteReaderPlugin.
Definition at line 72 of file AbstractImageProcessor.cs.
Referenced by ImageResizer.Resizing.AbstractImageProcessor.GetStream().
{
            path = null; //Init so the compiler doesn't complain
            restoreStreamPosition = false;
            if (exts != null) foreach (AbstractImageProcessor p in exts) {
                bool disposeS = disposeStream; //Copy the referenced boolean. Only allow plugins who return a stream to change its value
                Stream s = p.GetStream(source, settings, ref disposeS, out path, out restoreStreamPosition);
                if (s != null) {
                    disposeStream = disposeS;
                    return s;
                }
            }
            return null;
        }
virtual RequestedAction ImageResizer.Resizing.AbstractImageProcessor.Layout (ImageState s) [inline, protected, virtual]
Process.3(Layout).0: This is the last point at which points to translate should be added. Only return RequestedAction.Cancel if you wish to replace the entire Layout sequence logic.
Parameters:
s
Reimplemented in ImageResizer.ImageBuilder.
Definition at line 230 of file AbstractImageProcessor.cs.
Referenced by ImageResizer.Resizing.AbstractImageProcessor.Layout().
{
            if (exts != null) foreach (AbstractImageProcessor p in exts) if (p.Layout(s) == RequestedAction.Cancel) return RequestedAction.Cancel;
            return RequestedAction.None;
        }
virtual RequestedAction ImageResizer.Resizing.AbstractImageProcessor.LayoutBorder (ImageState s) [inline, protected, virtual]
Process.3(Layout).6: Ring "border" is added to the layout.
Parameters:
s
Reimplemented in ImageResizer.ImageBuilder.
Definition at line 287 of file AbstractImageProcessor.cs.
Referenced by ImageResizer.Resizing.AbstractImageProcessor.LayoutBorder().
{
            if (exts != null)
                foreach (AbstractImageProcessor p in exts)
                    if (p.LayoutBorder(s) == RequestedAction.Cancel)
                        return RequestedAction.Cancel;
            return RequestedAction.None;
        }
virtual RequestedAction ImageResizer.Resizing.AbstractImageProcessor.LayoutEffects (ImageState s) [inline, protected, virtual]
Process.3(Layout).8: Effects such as 'shadow' are added here.
Parameters:
s
Reimplemented in ImageResizer.Plugins.Basic.DropShadow.
Definition at line 311 of file AbstractImageProcessor.cs.
Referenced by ImageResizer.Resizing.AbstractImageProcessor.LayoutEffects().
{
            if (exts != null)
                foreach (AbstractImageProcessor p in exts)
                    if (p.LayoutEffects(s) == RequestedAction.Cancel)
                        return RequestedAction.Cancel;
            return RequestedAction.None;
        }
virtual RequestedAction ImageResizer.Resizing.AbstractImageProcessor.LayoutImage (ImageState s) [inline, protected, virtual]
Process.3(Layout).2: Rings 'image' and 'imageArea' are added to the layout.
Parameters:
s
Reimplemented in ImageResizer.ImageBuilder, ImageResizer.Plugins.WpfBuilder.WpfBuilderPlugin, ImageResizer.Plugins.SeamCarving.SeamCarvingPlugin, ImageResizer.Plugins.CropAround.CropAroundPlugin, and ImageResizer.Plugins.WhitespaceTrimmer.WhitespaceTrimmerPlugin.
Definition at line 248 of file AbstractImageProcessor.cs.
Referenced by ImageResizer.Resizing.AbstractImageProcessor.LayoutImage().
{
            if (exts != null) foreach (AbstractImageProcessor p in exts) if (p.LayoutImage(s) == RequestedAction.Cancel) return RequestedAction.Cancel;
            return RequestedAction.None;
        }
virtual RequestedAction ImageResizer.Resizing.AbstractImageProcessor.LayoutMargin (ImageState s) [inline, protected, virtual]
Process.3(Layout).10: Margins are added to the layout.
Parameters:
s
Reimplemented in ImageResizer.ImageBuilder.
Definition at line 335 of file AbstractImageProcessor.cs.
Referenced by ImageResizer.Resizing.AbstractImageProcessor.LayoutMargin().
{
            if (exts != null)
                foreach (AbstractImageProcessor p in exts)
                    if (p.LayoutMargin(s) == RequestedAction.Cancel)
                        return RequestedAction.Cancel;
            return RequestedAction.None;
        }
virtual RequestedAction ImageResizer.Resizing.AbstractImageProcessor.LayoutNormalize (ImageState s) [inline, protected, virtual]
Process.3(Layout).anytime: Occurs when the layout is normalized to 0,0. May be called anytime during Layout()
Parameters:
s
Reimplemented in ImageResizer.ImageBuilder.
Definition at line 383 of file AbstractImageProcessor.cs.
Referenced by ImageResizer.Resizing.AbstractImageProcessor.LayoutNormalize().
{
            if (exts != null)
                foreach (AbstractImageProcessor p in exts)
                    if (p.LayoutNormalize(s) == RequestedAction.Cancel)
                        return RequestedAction.Cancel;
            return RequestedAction.None;
        }
virtual RequestedAction ImageResizer.Resizing.AbstractImageProcessor.LayoutPadding (ImageState s) [inline, protected, virtual]
Process.3(Layout).4: Ring "padding" is added to the layout.
Parameters:
s
Reimplemented in ImageResizer.ImageBuilder.
Definition at line 266 of file AbstractImageProcessor.cs.
Referenced by ImageResizer.Resizing.AbstractImageProcessor.LayoutPadding().
{
            if (exts != null) foreach (AbstractImageProcessor p in exts) if (p.LayoutPadding(s) == RequestedAction.Cancel) return RequestedAction.Cancel;
            return RequestedAction.None;
        }
virtual RequestedAction ImageResizer.Resizing.AbstractImageProcessor.LayoutRotate (ImageState s) [inline, protected, virtual]
Process.3(Layout).anytime: Occurs when the layout is rotated. May be called anytime during Layout()
Parameters:
s
Reimplemented in ImageResizer.ImageBuilder.
Definition at line 359 of file AbstractImageProcessor.cs.
Referenced by ImageResizer.Resizing.AbstractImageProcessor.LayoutRotate().
{
            if (exts != null)
                foreach (AbstractImageProcessor p in exts)
                    if (p.LayoutRotate(s) == RequestedAction.Cancel)
                        return RequestedAction.Cancel;
            return RequestedAction.None;
        }
virtual RequestedAction ImageResizer.Resizing.AbstractImageProcessor.LayoutRound (ImageState s) [inline, protected, virtual]
Process.3(Layout).anytime: Occurs when the layout point values are rounded to integers. May be called anytime during Layout()
Parameters:
s
Reimplemented in ImageResizer.ImageBuilder.
Definition at line 407 of file AbstractImageProcessor.cs.
Referenced by ImageResizer.Resizing.AbstractImageProcessor.LayoutRound().
{
            if (exts != null)
                foreach (AbstractImageProcessor p in exts)
                    if (p.LayoutRound(s) == RequestedAction.Cancel)
                        return RequestedAction.Cancel;
            return RequestedAction.None;
        }
virtual RequestedAction ImageResizer.Resizing.AbstractImageProcessor.OnProcess (ImageState s) [inline, protected, virtual]
Process.0 First step of the Process() method. Can replace the entire Process method if RequestAction.Cancel is returned. Can be used to add points to translate (for image maps), and also to modify the settings.
Parameters:
s
Definition at line 203 of file AbstractImageProcessor.cs.
Referenced by ImageResizer.Resizing.AbstractImageProcessor.OnProcess().
{
            if (exts != null) foreach (AbstractImageProcessor p in exts) if (p.OnProcess(s) == RequestedAction.Cancel) return RequestedAction.Cancel;
            return RequestedAction.None;
        }
virtual RequestedAction ImageResizer.Resizing.AbstractImageProcessor.PostCreateImageAttributes (ImageState s) [inline, protected, virtual]
Process.5(Render).8: The ImageAttributes instance exists and can be modified or replaced.
Parameters:
s
Reimplemented in ImageResizer.Plugins.SimpleFilters.SimpleFilters.
Definition at line 542 of file AbstractImageProcessor.cs.
Referenced by ImageResizer.Resizing.AbstractImageProcessor.PostCreateImageAttributes().
{
            if (exts != null)
                foreach (AbstractImageProcessor p in exts)
                    if (p.PostCreateImageAttributes(s) == RequestedAction.Cancel)
                        return RequestedAction.Cancel;
            return RequestedAction.None;
        }
virtual RequestedAction ImageResizer.Resizing.AbstractImageProcessor.PostDecodeStream (ref Bitmap img, ResizeSettings settings) [inline, protected, virtual]
Extend this to modify the Bitmap instance after it has been decoded by DecodeStream or DecodeStreamFailed.
Reimplemented in ImageResizer.Plugins.Basic.AutoRotate.
Definition at line 127 of file AbstractImageProcessor.cs.
Referenced by ImageResizer.Resizing.AbstractImageProcessor.PostDecodeStream().
{
            if (exts != null) foreach (AbstractImageProcessor p in exts) if (p.PostDecodeStream(ref img, settings) == RequestedAction.Cancel) return RequestedAction.Cancel;
            return RequestedAction.None;
        }
virtual RequestedAction ImageResizer.Resizing.AbstractImageProcessor.PostFlushChanges (ImageState s) [inline, protected, virtual]
Process.5(Render).18: Changes have been flushed to the bitmap, but the final bitmap has not been flipped yet.
Parameters:
s
Definition at line 658 of file AbstractImageProcessor.cs.
Referenced by ImageResizer.Resizing.AbstractImageProcessor.PostFlushChanges().
{
            if (exts != null)
                foreach (AbstractImageProcessor p in exts)
                    if (p.PostFlushChanges(s) == RequestedAction.Cancel)
                        return RequestedAction.Cancel;
            return RequestedAction.None;
        }
virtual RequestedAction ImageResizer.Resizing.AbstractImageProcessor.PostLayoutBorder (ImageState s) [inline, protected, virtual]
Process.3(Layout).7: Add rings here to insert them between the border and the effect rings.
Parameters:
s
Definition at line 299 of file AbstractImageProcessor.cs.
Referenced by ImageResizer.Resizing.AbstractImageProcessor.PostLayoutBorder().
{
            if (exts != null)
                foreach (AbstractImageProcessor p in exts)
                    if (p.PostLayoutBorder(s) == RequestedAction.Cancel)
                        return RequestedAction.Cancel;
            return RequestedAction.None;
        }
virtual RequestedAction ImageResizer.Resizing.AbstractImageProcessor.PostLayoutEffects (ImageState s) [inline, protected, virtual]
Process.3(Layout).9: Add rings here to insert them between the effects and the margin.
Parameters:
s
Definition at line 323 of file AbstractImageProcessor.cs.
Referenced by ImageResizer.Resizing.AbstractImageProcessor.PostLayoutEffects().
{
            if (exts != null)
                foreach (AbstractImageProcessor p in exts)
                    if (p.PostLayoutEffects(s) == RequestedAction.Cancel)
                        return RequestedAction.Cancel;
            return RequestedAction.None;
        }
virtual RequestedAction ImageResizer.Resizing.AbstractImageProcessor.PostLayoutImage (ImageState s) [inline, protected, virtual]
Process.3(Layout).3: Add rings here to insert them between the image area and the padding.
Parameters:
s
Reimplemented in ImageResizer.Plugins.SeamCarving.SeamCarvingPlugin, ImageResizer.Plugins.WhitespaceTrimmer.WhitespaceTrimmerPlugin, and ImageResizer.Plugins.Basic.SizeLimiting.
Definition at line 257 of file AbstractImageProcessor.cs.
Referenced by ImageResizer.Resizing.AbstractImageProcessor.PostLayoutImage().
{
            if (exts != null) foreach (AbstractImageProcessor p in exts) if (p.PostLayoutImage(s) == RequestedAction.Cancel) return RequestedAction.Cancel;
            return RequestedAction.None;
        }
virtual RequestedAction ImageResizer.Resizing.AbstractImageProcessor.PostLayoutMargin (ImageState s) [inline, protected, virtual]
Process.3(Layout).11: Add rings here to insert them around the margin. Rings will be outermost.
Parameters:
s
Definition at line 347 of file AbstractImageProcessor.cs.
Referenced by ImageResizer.Resizing.AbstractImageProcessor.PostLayoutMargin().
{
            if (exts != null)
                foreach (AbstractImageProcessor p in exts)
                    if (p.PostLayoutMargin(s) == RequestedAction.Cancel)
                        return RequestedAction.Cancel;
            return RequestedAction.None;
        }
virtual RequestedAction ImageResizer.Resizing.AbstractImageProcessor.PostLayoutNormalize (ImageState s) [inline, protected, virtual]
Process.3(Layout).anytime: Occurs after the layout is normalized. May be called anytime during Layout()
Parameters:
s
Definition at line 395 of file AbstractImageProcessor.cs.
Referenced by ImageResizer.Resizing.AbstractImageProcessor.PostLayoutNormalize().
{
            if (exts != null)
                foreach (AbstractImageProcessor p in exts)
                    if (p.PostLayoutNormalize(s) == RequestedAction.Cancel)
                        return RequestedAction.Cancel;
            return RequestedAction.None;
        }
virtual RequestedAction ImageResizer.Resizing.AbstractImageProcessor.PostLayoutPadding (ImageState s) [inline, protected, virtual]
Process.3(Layout).5: Add rings here to insert them between the padding and the border.
Parameters:
s
Definition at line 275 of file AbstractImageProcessor.cs.
Referenced by ImageResizer.Resizing.AbstractImageProcessor.PostLayoutPadding().
{
            if (exts != null)
                foreach (AbstractImageProcessor p in exts)
                    if (p.PostLayoutPadding(s) == RequestedAction.Cancel)
                        return RequestedAction.Cancel;
            return RequestedAction.None;
        }
virtual RequestedAction ImageResizer.Resizing.AbstractImageProcessor.PostLayoutRotate (ImageState s) [inline, protected, virtual]
Process.3(Layout).anytime: Occurs after the layout is rotated. May be called anytime during Layout()
Parameters:
s
Definition at line 371 of file AbstractImageProcessor.cs.
Referenced by ImageResizer.Resizing.AbstractImageProcessor.PostLayoutRotate().
{
            if (exts != null)
                foreach (AbstractImageProcessor p in exts)
                    if (p.PostLayoutRotate(s) == RequestedAction.Cancel)
                        return RequestedAction.Cancel;
            return RequestedAction.None;
        }
virtual RequestedAction ImageResizer.Resizing.AbstractImageProcessor.PostLayoutRound (ImageState s) [inline, protected, virtual]
Process.3(Layout).anytime: Occurs after the layout point values are rounded to integers. May be called anytime during Layout()
Parameters:
s
Definition at line 419 of file AbstractImageProcessor.cs.
Referenced by ImageResizer.Resizing.AbstractImageProcessor.PostLayoutRound().
{
            if (exts != null)
                foreach (AbstractImageProcessor p in exts)
                    if (p.PostLayoutRound(s) == RequestedAction.Cancel)
                        return RequestedAction.Cancel;
            return RequestedAction.None;
        }
virtual RequestedAction ImageResizer.Resizing.AbstractImageProcessor.PostPrepareSourceBitmap (ImageState s) [inline, protected, virtual]
Process.2 Extend this to apply any pre-processing to the source bitmap that needs to occur before Layout begins.
Parameters:
s
Reimplemented in ImageResizer.Plugins.Faces.FacesPlugin.
Definition at line 220 of file AbstractImageProcessor.cs.
Referenced by ImageResizer.Resizing.AbstractImageProcessor.PostPrepareSourceBitmap().
{
            if (exts != null) foreach (AbstractImageProcessor p in exts) if (p.PostPrepareSourceBitmap(s) == RequestedAction.Cancel) return RequestedAction.Cancel;
            return RequestedAction.None;
        }
virtual RequestedAction ImageResizer.Resizing.AbstractImageProcessor.PostRenderBackground (ImageState s) [inline, protected, virtual]
Process.5(Render).2 After the background color is rendered.
Parameters:
s
Reimplemented in ImageResizer.Plugins.Watermark.WatermarkPlugin, and ImageResizer.Plugins.Watermark.WatermarkPlugin.
Definition at line 475 of file AbstractImageProcessor.cs.
Referenced by ImageResizer.Resizing.AbstractImageProcessor.PostRenderBackground().
{
            if (exts != null)
                foreach (AbstractImageProcessor p in exts)
                    if (p.PostRenderBackground(s) == RequestedAction.Cancel)
                        return RequestedAction.Cancel;
            return RequestedAction.None;
        }
virtual RequestedAction ImageResizer.Resizing.AbstractImageProcessor.PostRenderBorder (ImageState s) [inline, protected, virtual]
Process.5(Render).13: After the border is drawn.
Parameters:
s
Definition at line 599 of file AbstractImageProcessor.cs.
Referenced by ImageResizer.Resizing.AbstractImageProcessor.PostRenderBorder().
{
            if (exts != null)
                foreach (AbstractImageProcessor p in exts)
                    if (p.PostRenderBorder(s) == RequestedAction.Cancel)
                        return RequestedAction.Cancel;
            return RequestedAction.None;
        }
virtual RequestedAction ImageResizer.Resizing.AbstractImageProcessor.PostRenderEffects (ImageState s) [inline, protected, virtual]
Process.5(Render).4 After outer effects are rendered.
Parameters:
s
Definition at line 498 of file AbstractImageProcessor.cs.
Referenced by ImageResizer.Resizing.AbstractImageProcessor.PostRenderEffects().
{
            if (exts != null)
                foreach (AbstractImageProcessor p in exts)
                    if (p.PostRenderEffects(s) == RequestedAction.Cancel)
                        return RequestedAction.Cancel;
            return RequestedAction.None;
        }
virtual RequestedAction ImageResizer.Resizing.AbstractImageProcessor.PostRenderImage (ImageState s) [inline, protected, virtual]
Process.5(Render).11: After the image is drawn.
Parameters:
s
Reimplemented in ImageResizer.Plugins.SimpleFilters.SimpleFilters, ImageResizer.Plugins.Faces.FacesPlugin, ImageResizer.Plugins.RedEye.RedEyePlugin, and ImageResizer.Plugins.AdvancedFilters.AdvancedFilters.
Definition at line 577 of file AbstractImageProcessor.cs.
Referenced by ImageResizer.Resizing.AbstractImageProcessor.PostRenderImage().
{
            if (exts != null)
                foreach (AbstractImageProcessor p in exts)
                    if (p.PostRenderImage(s) == RequestedAction.Cancel)
                        return RequestedAction.Cancel;
            return RequestedAction.None;
        }
virtual RequestedAction ImageResizer.Resizing.AbstractImageProcessor.PostRenderPadding (ImageState s) [inline, protected, virtual]
Process.5(Render).6 After image padding is drawn.
Parameters:
s
Definition at line 520 of file AbstractImageProcessor.cs.
Referenced by ImageResizer.Resizing.AbstractImageProcessor.PostRenderPadding().
{
            if (exts != null)
                foreach (AbstractImageProcessor p in exts)
                    if (p.PostRenderPadding(s) == RequestedAction.Cancel)
                        return RequestedAction.Cancel;
            return RequestedAction.None;
        }
virtual void ImageResizer.Resizing.AbstractImageProcessor.PreAcquireStream (ref object dest, ResizeSettings settings) [inline, protected, virtual]
Extend this to allow additional types of *destination* objects to be accepted by transforming them into a stream.
Parameters:
dest
settings
Definition at line 140 of file AbstractImageProcessor.cs.
Referenced by ImageResizer.Resizing.AbstractImageProcessor.PreAcquireStream().
{
            if (exts != null) foreach (AbstractImageProcessor p in exts) p.PreAcquireStream(ref dest, settings);
        }
virtual RequestedAction ImageResizer.Resizing.AbstractImageProcessor.PreFlushChanges (ImageState s) [inline, protected, virtual]
Process.5(Render).16: Called before changes are flushed and the graphics object is destroyed.
Parameters:
s
Reimplemented in ImageResizer.Plugins.Basic.Trial.
Definition at line 634 of file AbstractImageProcessor.cs.
Referenced by ImageResizer.Resizing.AbstractImageProcessor.PreFlushChanges().
{
            if (exts != null)
                foreach (AbstractImageProcessor p in exts)
                    if (p.PreFlushChanges(s) == RequestedAction.Cancel)
                        return RequestedAction.Cancel;
            return RequestedAction.None;
        }
virtual void ImageResizer.Resizing.AbstractImageProcessor.PreLoadImage (ref object source, ref string path, ref bool disposeSource, ref ResizeSettings settings) [inline, protected, virtual]
Extend this to allow additional types of source objects to be accepted by transforming them into Bitmap instances.
Parameters:
source
path
disposeSource
settings
Definition at line 59 of file AbstractImageProcessor.cs.
Referenced by ImageResizer.ImageBuilder.LoadImage(), and ImageResizer.Resizing.AbstractImageProcessor.PreLoadImage().
{
            if (exts != null) foreach (AbstractImageProcessor p in exts) p.PreLoadImage(ref source, ref path, ref disposeSource, ref settings);
        }
virtual RequestedAction ImageResizer.Resizing.AbstractImageProcessor.PrepareDestinationBitmap (ImageState s) [inline, protected, virtual]
Process.4: The destination bitmap is created and sized based destSize. A graphics object is initialized for rendering.
Parameters:
s
Reimplemented in ImageResizer.ImageBuilder, ImageResizer.Plugins.Watermark.WatermarkPlugin, and ImageResizer.Plugins.Basic.SizeLimiting.
Definition at line 442 of file AbstractImageProcessor.cs.
Referenced by ImageResizer.Resizing.AbstractImageProcessor.PrepareDestinationBitmap().
{
            if (exts != null)
                foreach (AbstractImageProcessor p in exts)
                    if (p.PrepareDestinationBitmap(s) == RequestedAction.Cancel)
                        return RequestedAction.Cancel;
            return RequestedAction.None;
        }
virtual RequestedAction ImageResizer.Resizing.AbstractImageProcessor.PrepareSourceBitmap (ImageState s) [inline, protected, virtual]
Process.1 Switches the bitmap to the correct frame or page, and applies source flipping commands.
Parameters:
s
Reimplemented in ImageResizer.ImageBuilder.
Definition at line 212 of file AbstractImageProcessor.cs.
Referenced by ImageResizer.Resizing.AbstractImageProcessor.PrepareSourceBitmap().
{
            if (exts != null) foreach (AbstractImageProcessor p in exts) if (p.PrepareSourceBitmap(s) == RequestedAction.Cancel) return RequestedAction.Cancel;
            return RequestedAction.None;
        }
virtual RequestedAction ImageResizer.Resizing.AbstractImageProcessor.PreRenderImage (ImageState s) [inline, protected, virtual]
Process.5(Render).9: Plugins have a chance to pre-process the source image before it gets rendered, and save it to s.preRenderBitmap.
Parameters:
s
Reimplemented in ImageResizer.Plugins.SeamCarving.SeamCarvingPlugin, ImageResizer.Plugins.AdvancedFilters.AdvancedFilters, ImageResizer.Plugins.FreeImageScaling.FreeImageScalingPlugin, and ImageResizer.Plugins.SimpleFilters.SimpleFilters.
Definition at line 554 of file AbstractImageProcessor.cs.
Referenced by ImageResizer.Resizing.AbstractImageProcessor.PreRenderImage().
{
            if (exts != null)
                foreach (AbstractImageProcessor p in exts)
                    if (p.PreRenderImage(s) == RequestedAction.Cancel)
                        return RequestedAction.Cancel;
            return RequestedAction.None;
        }
virtual RequestedAction ImageResizer.Resizing.AbstractImageProcessor.PreRenderOverlays (ImageState s) [inline, protected, virtual]
Process.5(Render).14: Any last-minute changes before watermarking or overlays are applied.
Parameters:
s
Definition at line 611 of file AbstractImageProcessor.cs.
Referenced by ImageResizer.Resizing.AbstractImageProcessor.PreRenderOverlays().
{
            if (exts != null)
                foreach (AbstractImageProcessor p in exts)
                    if (p.PreRenderOverlays(s) == RequestedAction.Cancel)
                        return RequestedAction.Cancel;
            return RequestedAction.None;
        }
virtual RequestedAction ImageResizer.Resizing.AbstractImageProcessor.ProcessFinalBitmap (ImageState s) [inline, protected, virtual]
Process.6: Non-rendering changes to the bitmap object occur here, such as flipping. The graphics object is unavailable.
Parameters:
s
Reimplemented in ImageResizer.ImageBuilder.
Definition at line 670 of file AbstractImageProcessor.cs.
Referenced by ImageResizer.Resizing.AbstractImageProcessor.ProcessFinalBitmap().
{
            if (exts != null)
                foreach (AbstractImageProcessor p in exts)
                    if (p.ProcessFinalBitmap(s) == RequestedAction.Cancel)
                        return RequestedAction.Cancel;
            return RequestedAction.None;
        }
virtual RequestedAction ImageResizer.Resizing.AbstractImageProcessor.Render (ImageState s) [inline, protected, virtual]
Process.5(Render) Rendering. Do not return RequestedAction.Cancel unless you want to replace the entire rendering system.
Parameters:
s
Reimplemented in ImageResizer.ImageBuilder, ImageResizer.Plugins.Faces.FacesPlugin, and ImageResizer.Plugins.RedEye.RedEyePlugin.
Definition at line 453 of file AbstractImageProcessor.cs.
Referenced by ImageResizer.Resizing.AbstractImageProcessor.Render().
{
            if (exts != null)
                foreach (AbstractImageProcessor p in exts)
                    if (p.Render(s) == RequestedAction.Cancel)
                        return RequestedAction.Cancel;
            return RequestedAction.None;
        }
virtual RequestedAction ImageResizer.Resizing.AbstractImageProcessor.RenderBackground (ImageState s) [inline, protected, virtual]
Process.5(Render).1 The background color is rendered.
Parameters:
s
Reimplemented in ImageResizer.ImageBuilder.
Definition at line 464 of file AbstractImageProcessor.cs.
Referenced by ImageResizer.Resizing.AbstractImageProcessor.RenderBackground().
{
            if (exts != null)
                foreach (AbstractImageProcessor p in exts)
                    if (p.RenderBackground(s) == RequestedAction.Cancel)
                        return RequestedAction.Cancel;
            return RequestedAction.None;
        }
virtual RequestedAction ImageResizer.Resizing.AbstractImageProcessor.RenderBorder (ImageState s) [inline, protected, virtual]
Process.5(Render).12: The border is rendered.
Parameters:
s
Reimplemented in ImageResizer.ImageBuilder.
Definition at line 588 of file AbstractImageProcessor.cs.
Referenced by ImageResizer.Resizing.AbstractImageProcessor.RenderBorder().
{
            if (exts != null)
                foreach (AbstractImageProcessor p in exts)
                    if (p.RenderBorder(s) == RequestedAction.Cancel)
                        return RequestedAction.Cancel;
            return RequestedAction.None;
        }
virtual RequestedAction ImageResizer.Resizing.AbstractImageProcessor.RenderEffects (ImageState s) [inline, protected, virtual]
Process.5(Render).3 Effects (such as a drop shadow or outer glow) are rendered.
Parameters:
s
Reimplemented in ImageResizer.Plugins.Basic.DropShadow.
Definition at line 487 of file AbstractImageProcessor.cs.
Referenced by ImageResizer.Resizing.AbstractImageProcessor.RenderEffects().
{
            if (exts != null)
                foreach (AbstractImageProcessor p in exts)
                    if (p.RenderEffects(s) == RequestedAction.Cancel)
                        return RequestedAction.Cancel;
            return RequestedAction.None;
        }
virtual RequestedAction ImageResizer.Resizing.AbstractImageProcessor.RenderImage (ImageState s) [inline, protected, virtual]
Process.5(Render).10: The image is copied to the destination parallelogram specified by ring 'image'.
Parameters:
s
Reimplemented in ImageResizer.ImageBuilder, and ImageResizer.Plugins.Basic.SpeedOrQuality.
Definition at line 566 of file AbstractImageProcessor.cs.
Referenced by ImageResizer.Resizing.AbstractImageProcessor.RenderImage().
{
            if (exts != null)
                foreach (AbstractImageProcessor p in exts)
                    if (p.RenderImage(s) == RequestedAction.Cancel)
                        return RequestedAction.Cancel;
            return RequestedAction.None;
        }
virtual RequestedAction ImageResizer.Resizing.AbstractImageProcessor.RenderOverlays (ImageState s) [inline, protected, virtual]
Process.5(Render).15: Watermarks can be rendered here. All image processing should be done.
Parameters:
s
Reimplemented in ImageResizer.Plugins.Watermark.WatermarkPlugin, and ImageResizer.Plugins.Watermark.WatermarkPlugin.
Definition at line 623 of file AbstractImageProcessor.cs.
Referenced by ImageResizer.Resizing.AbstractImageProcessor.RenderOverlays().
{
            if (exts != null)
                foreach (AbstractImageProcessor p in exts)
                    if (p.RenderOverlays(s) == RequestedAction.Cancel)
                        return RequestedAction.Cancel;
            return RequestedAction.None;
        }
virtual RequestedAction ImageResizer.Resizing.AbstractImageProcessor.RenderPadding (ImageState s) [inline, protected, virtual]
Process.5(Render).5 Image padding is drawn.
Parameters:
s
Reimplemented in ImageResizer.ImageBuilder.
Definition at line 509 of file AbstractImageProcessor.cs.
Referenced by ImageResizer.Resizing.AbstractImageProcessor.RenderPadding().
{
            if (exts != null)
                foreach (AbstractImageProcessor p in exts)
                    if (p.RenderPadding(s) == RequestedAction.Cancel)
                        return RequestedAction.Cancel;
            return RequestedAction.None;
        }
Member Data Documentation
volatile IEnumerable<BuilderExtension> ImageResizer.Resizing.AbstractImageProcessor.exts [protected]
Contains the set of extensions that are called for every method.
Definition at line 50 of file AbstractImageProcessor.cs.
Referenced by ImageResizer.ImageBuilder.Copy().
The documentation for this class was generated from the following file:
C:/Users/Administrator/Documents/resizer/Core/Resizing/AbstractImageProcessor.cs