ImageResizer: ImageResizer.Resizing.LayoutBuilder Class Reference
ImageResizer.Resizing.LayoutBuilder Class Reference
Classes
class PointSet
Public Types
enum PointFlags { Ring = 1, Invisible = 2, Ignored = 4 }
enum PointTranslationBehavior { Exact, ClosestVisiblePoint, ClosestImagePoint, Empty }
Public Member Functions
PointSet AddRing (string name, PointF[] points)
bool ContainsRing (string name)
PointSet AddRing (string name, BoxPadding padding)
Inflates the last ring using the specified padding options. Returns the resulting ring object.
PointSet AddInvisiblePolygon (string name, PointF[] points)
Add points this way to see where they will occur on the destination image.
PointSet AddIgnoredPoints (string name, PointF[] points)
RectangleF GetBoundingBox ()
Gets a bounding box that encloses all rings that don't have ExcludeFromBoundingBox set.
void Rotate (double degrees, PointF origin)
Rotates all existing rings (Except those flagged ignore)
void Normalize (PointF origin)
Normalizes all rings and invisible polygons so that the outermost ring's bounding box starts at the specified orign.
void Round ()
void Scale (double factor, PointF origin)
Scales all rings and invisible polygons by the specified factor, around the specified point.
void Shift (RectangleF from, RectangleF to)
Translates and scales all rings and invisible polygons as specified.
Protected Attributes
Dictionary< string, PointSet > ring = new Dictionary<string, PointSet>(10, StringComparer.OrdinalIgnoreCase)
An ordered, named collection of polygons. pointsToTranslate, imageOuterEdge, imageAreaOuterEdge.
List< PointSet > ringList = new List<PointSet>(10)
Properties
PointF[] this[string key] [get, set]
Access and set the Point[] arrays of rings by key. Case-insensitive.
PointSet LastRing [get]
Returns the last ring that was added. Only returns PointSets where flags = Ring.
Detailed Description
Definition at line 9 of file LayoutBuilder.cs.
Member Enumeration Documentation
enum ImageResizer::Resizing::LayoutBuilder::PointFlags
Enumerator:
Ring
This polygon participates in the layout phase, and reserves space when added. Affected by all batch operations. Will be returned by LastRing until a new ring is added.
Invisible
Doesn't participate in layout, takes no space, but is affected by batch operations. Will never be returned by LastRing and ignored when calculating bounding boxes.
Ignored
Completely ignored by all operations, left intact.
Definition at line 11 of file LayoutBuilder.cs.
{
            /// <summary>
            /// This polygon participates in the layout phase, and reserves space when added. Affected by all batch operations. Will be returned by LastRing until a new ring is added.
            /// </summary>
            Ring = 1,
            /// <summary>
            /// Doesn't participate in layout, takes no space, but is affected by batch operations. Will never be returned by LastRing and ignored when calculating bounding boxes.
            /// </summary>
            Invisible = 2,
            /// <summary>
            /// Completely ignored by all operations, left intact.
            /// </summary>
            Ignored = 4
        }
Member Function Documentation
PointSet ImageResizer.Resizing.LayoutBuilder.AddInvisiblePolygon (string name, PointF[] points) [inline]
Add points this way to see where they will occur on the destination image.
Parameters:
name
points
Returns:
Definition at line 114 of file LayoutBuilder.cs.
Referenced by ImageResizer.Plugins.Basic.DropShadow.LayoutEffects(), ImageResizer.Plugins.Faces.FacesPlugin.PostPrepareSourceBitmap(), and ImageResizer.ImageBuilder.TranslatePoints().
{
            PointSet ps = new PointSet(points);
            ps.flags = PointFlags.Invisible;
            ring.Add(name, ps);
            ringList.Add(ps);
            return ps;
        }
PointSet ImageResizer.Resizing.LayoutBuilder.AddRing (string name, BoxPadding padding) [inline]
Inflates the last ring using the specified padding options. Returns the resulting ring object.
Parameters:
name
padding
Returns:
Definition at line 105 of file LayoutBuilder.cs.
{
            return AddRing(name, PolygonMath.InflatePoly(LastRing.points, padding.GetEdgeOffsets()));
        }
RectangleF ImageResizer.Resizing.LayoutBuilder.GetBoundingBox () [inline]
Gets a bounding box that encloses all rings that don't have ExcludeFromBoundingBox set.
Returns:
Definition at line 133 of file LayoutBuilder.cs.
Referenced by ImageResizer.ImageBuilder.EndLayout(), and ImageResizer.Plugins.Basic.SizeLimiting.PostLayoutImage().
{
            List<PointF> points = new List<PointF>(ring.Count * 5);
            foreach (PointSet val in ringList) {
                if (val.flags == PointFlags.Ring) points.AddRange(val.points);
            }
            return PolygonMath.GetBoundingBox(points.ToArray());
        }
void ImageResizer.Resizing.LayoutBuilder.Normalize (PointF origin) [inline]
Normalizes all rings and invisible polygons so that the outermost ring's bounding box starts at the specified orign.
Parameters:
origin
Returns:
Definition at line 158 of file LayoutBuilder.cs.
Referenced by ImageResizer.ImageBuilder.LayoutNormalize().
{
            PointF offset = GetBoundingBox().Location;
            offset.X *= -1;
            offset.Y *= -1;
            foreach (PointSet ps in ringList)
                if (ps.flags != PointFlags.Ignored) ps.points = PolygonMath.MovePoly(ps.points, offset);
        }
void ImageResizer.Resizing.LayoutBuilder.Rotate (double degrees, PointF origin) [inline]
Rotates all existing rings (Except those flagged ignore)
Parameters:
degrees
origin
Returns:
Definition at line 147 of file LayoutBuilder.cs.
Referenced by ImageResizer.ImageBuilder.LayoutRotate().
{
            foreach (PointSet ps in ringList)
                if (ps.flags != PointFlags.Ignored) ps.points = PolygonMath.RotatePoly(ps.points, degrees, origin);
        }
void ImageResizer.Resizing.LayoutBuilder.Scale (double factor, PointF origin) [inline]
Scales all rings and invisible polygons by the specified factor, around the specified point.
Parameters:
factor
origin
Definition at line 178 of file LayoutBuilder.cs.
Referenced by ImageResizer.Plugins.Basic.SizeLimiting.PostLayoutImage().
{
            foreach (PointSet ps in ringList)
                if (ps.flags != PointFlags.Ignored) ps.points = PolygonMath.ScalePoints(ps.points, factor,factor, origin);
        }
void ImageResizer.Resizing.LayoutBuilder.Shift (RectangleF from, RectangleF to) [inline]
Translates and scales all rings and invisible polygons as specified.
Parameters:
from
to
Definition at line 188 of file LayoutBuilder.cs.
Referenced by ImageResizer.ImageBuilder.LayoutImage().
{
            PointF fromOrigin = new PointF(from.X + (from.Width /2), from.Y + (from.Height /2));
            PointF toOrigin = new PointF(to.X + (to.Width /2), to.Y + (to.Height /2));
            PointF offset = new PointF(toOrigin.X - fromOrigin.X,toOrigin.Y - fromOrigin.Y);
            double xd = to.Width / from.Width;
            double yd = to.Height / from.Height;
            //Offset points
            foreach (PointSet ps in ringList)
                if (ps.flags != PointFlags.Ignored) ps.points = PolygonMath.MovePoly(ps.points,offset );
            //Scale points
            foreach (PointSet ps in ringList)
                if (ps.flags != PointFlags.Ignored) ps.points = PolygonMath.ScalePoints(ps.points, xd,yd, toOrigin );
        }
Member Data Documentation
Dictionary<string, PointSet> ImageResizer.Resizing.LayoutBuilder.ring = new Dictionary<string, PointSet>(10, StringComparer.OrdinalIgnoreCase) [protected]
An ordered, named collection of polygons. pointsToTranslate, imageOuterEdge, imageAreaOuterEdge.
Definition at line 59 of file LayoutBuilder.cs.
Property Documentation
PointSet ImageResizer.Resizing.LayoutBuilder.LastRing [get]
Returns the last ring that was added. Only returns PointSets where flags = Ring.
Definition at line 78 of file LayoutBuilder.cs.
Referenced by ImageResizer.Plugins.Basic.DropShadow.LayoutEffects(), and ImageResizer.ImageBuilder.RenderBackground().
PointF [] ImageResizer.Resizing.LayoutBuilder.this[string key] [get, set]
Access and set the Point[] arrays of rings by key. Case-insensitive.
Parameters:
key
Returns:
Definition at line 66 of file LayoutBuilder.cs.
The documentation for this class was generated from the following file:
C:/Users/Administrator/Documents/resizer/Core/Resizing/LayoutBuilder.cs