ImageResizer: ImageResizer.Util.Utils Class Reference
ImageResizer.Util.Utils Class Reference
Static Public Member Functions
static Color parseColor (string value, Color defaultValue)
static string writeColor (Color value)
static double[] parseList (string text, double defaultValue)
Parses lists in the form "3,4,5,2,5" and "(3,4,40,50)". If a number cannot be parsed (i.e, number 2 in "5,,2,3") defaultValue is used.
static int getInt (NameValueCollection q, string name, int defaultValue)
static float getFloat (NameValueCollection q, string name, float defaultValue)
static double getDouble (NameValueCollection q, string name, double defaultValue)
static bool getBool (NameValueCollection q, string name, bool defaultValue)
static T parseEnum< T > (string value, T defaultValue)
static void copyStream (Stream source, Stream dest)
Copies all remaining data from 'source' to 'dest'.
static RotateFlipType parseFlip (string sFlip)
Returns RotateNoneFlipNone if not a recognized value.
static double parseRotate (string s)
Returns 0 if not a recognized value. Rounds the value to 0, 90, 180, or 270.
static double normalizeTo90Intervals (double d)
static RotateFlipType combineFlipAndRotate (RotateFlipType flip, double angle)
static string writeFlip (RotateFlipType flip)
Throws an exception if the specified value is unsupported. Rotation values are not supported, and should be specified with the Rotate or srcRotate command.
static StretchMode parseStretch (string value)
static string writeStretch (StretchMode value)
static KeyValuePair< CropUnits,
double > parseCropUnits (string value)
static string writeCropUnits (KeyValuePair< CropUnits, double > value)
static ScaleMode parseScale (string value)
static string writeScale (ScaleMode value)
static KeyValuePair< CropMode,
double[]> parseCrop (string value)
static string writeCrop (CropMode mode, double[] coords)
static BoxPadding parsePadding (string value)
Parses padding, allowing syntax (all) and (left, top, right, bottom). Parens are optional.
static PointF parsePointF (string value, PointF defaultValue)
static string writePadding (BoxPadding p)
static void DrawOuterGradient (Graphics g, PointF[] poly, Color inner, Color outer, float width)
Draws a gradient around the specified polygon. Fades from 'inner' to 'outer' over a distance of 'width' pixels.
Detailed Description
Definition at line 14 of file Utils.cs.
Member Function Documentation
static void ImageResizer.Util.Utils.copyStream (Stream source, Stream dest) [inline, static]
Copies all remaining data from 'source' to 'dest'.
Parameters:
source
dest
Definition at line 122 of file Utils.cs.
Referenced by ImageResizer.Mvc.ImageRequestAction.ExecuteVirtualFileResult(), and ImageResizer.InterceptModule.HandleRequest().
{
            byte[] buffer = new byte[32768];//8Kb
            while (true) {
                int len = source.Read(buffer, 0, buffer.Length);
                if (len <= 0) break;
                dest.Write(buffer, 0, len);
            }
        }
static void ImageResizer.Util.Utils.DrawOuterGradient (Graphics g, PointF[] poly, Color inner, Color outer, float width) [inline, static]
Draws a gradient around the specified polygon. Fades from 'inner' to 'outer' over a distance of 'width' pixels.
Parameters:
g
poly
inner
outer
width
Definition at line 329 of file Utils.cs.
Referenced by ImageResizer.Plugins.Basic.DropShadow.RenderEffects().
{
            //PointF[,] corners = PolygonMath.RoundPoints(PolygonMath.GetCorners(poly, width));
            //PointF[,] sides = PolygonMath.RoundPoints(PolygonMath.GetSides(poly, width));
            PointF[,] corners = PolygonMath.GetCorners(poly, width);
            PointF[,] sides = PolygonMath.GetSides(poly, width);
            //Overlapping these causes darker areas... Dont use InflatePoly
            //Paint corners
            for (int i = 0; i <= corners.GetUpperBound(0); i++) {
                PointF[] pts = PolygonMath.GetSubArray(corners, i);
                using (Brush b = PolygonMath.GenerateRadialBrush(inner, outer, pts[0], width + 1)) {
                    g.FillPolygon(b, pts);
                }
            }
            //Paint sides
            for (int i = 0; i <= sides.GetUpperBound(0); i++) {
                PointF[] pts = PolygonMath.GetSubArray(sides, i);
                using (LinearGradientBrush b = new LinearGradientBrush(pts[3], pts[0], inner, outer)) {
                    b.SetSigmaBellShape(1);
                    b.WrapMode = WrapMode.TileFlipXY;
                    g.FillPolygon(b, pts);
                }
            }
        }
static RotateFlipType ImageResizer.Util.Utils.parseFlip (string sFlip) [inline, static]
Returns RotateNoneFlipNone if not a recognized value.
Parameters:
sFlip
Returns:
Definition at line 139 of file Utils.cs.
{
            if (!string.IsNullOrEmpty(sFlip)) {
                if ("none".Equals(sFlip, StringComparison.OrdinalIgnoreCase))
                    return RotateFlipType.RotateNoneFlipNone;
                else if (sFlip.Equals("h", StringComparison.OrdinalIgnoreCase))
                    return RotateFlipType.RotateNoneFlipX;
                else if (sFlip.Equals("x", StringComparison.OrdinalIgnoreCase))
                    return RotateFlipType.RotateNoneFlipX;
                else if (sFlip.Equals("v", StringComparison.OrdinalIgnoreCase))
                    return RotateFlipType.RotateNoneFlipY;
                else if (sFlip.Equals("y", StringComparison.OrdinalIgnoreCase))
                    return RotateFlipType.RotateNoneFlipY;
                else if (sFlip.Equals("both", StringComparison.OrdinalIgnoreCase))
                    return RotateFlipType.RotateNoneFlipXY;
                else if (sFlip.Equals("xy", StringComparison.OrdinalIgnoreCase))
                    return RotateFlipType.RotateNoneFlipXY;
            }
            return RotateFlipType.RotateNoneFlipNone;
        }
static double [] ImageResizer.Util.Utils.parseList (string text, double defaultValue) [inline, static]
Parses lists in the form "3,4,5,2,5" and "(3,4,40,50)". If a number cannot be parsed (i.e, number 2 in "5,,2,3") defaultValue is used.
Parameters:
text
defaultValue
Returns:
Definition at line 57 of file Utils.cs.
{
            text = text.Trim(' ', '(', ')');
            string[] parts = text.Split(new char[] { ',' }, StringSplitOptions.None);
            double[] vals = new double[parts.Length];
            for (int i = 0; i < parts.Length; i++) {
                if (!double.TryParse(parts[i], out vals[i]))
                    vals[i] = defaultValue;
            }
            return vals;
        }
static BoxPadding ImageResizer.Util.Utils.parsePadding (string value) [inline, static]
Parses padding, allowing syntax (all) and (left, top, right, bottom). Parens are optional.
Parameters:
value
Returns:
Definition at line 296 of file Utils.cs.
{
            //Default to none if null
            if (string.IsNullOrEmpty(value)) return BoxPadding.Empty;
            double[] coords = parseList(value, 0);
            if (coords.Length == 1) return new BoxPadding(coords[0]);
            if (coords.Length == 4) return new BoxPadding(coords[0], coords[1], coords[2], coords[3]);
            return BoxPadding.Empty; //Unrecognized value;
        }
static double ImageResizer.Util.Utils.parseRotate (string s) [inline, static]
Returns 0 if not a recognized value. Rounds the value to 0, 90, 180, or 270.
Parameters:
sFlip
Returns:
Definition at line 165 of file Utils.cs.
Referenced by ImageResizer.ImageBuilder.PrepareSourceBitmap().
{
            if (!string.IsNullOrEmpty(s)) {
                double temp;
                if (!double.TryParse(s, out temp)) return 0;
                return normalizeTo90Intervals(temp);
            }
            return 0;
        }
static string ImageResizer.Util.Utils.writeFlip (RotateFlipType flip) [inline, static]
Throws an exception if the specified value is unsupported. Rotation values are not supported, and should be specified with the Rotate or srcRotate command.
Returns:
Definition at line 213 of file Utils.cs.
{
            if (flip == RotateFlipType.RotateNoneFlipNone) return "none";
            if (flip == RotateFlipType.RotateNoneFlipX) return "x";
            if (flip == RotateFlipType.RotateNoneFlipY) return "y";
            if (flip == RotateFlipType.RotateNoneFlipXY) return "xy";
            throw new ArgumentException("Valid flip values are RotateNoneFlipNone, RotateNoneFlipX, RotateNoneFlipY, and RotateNoneFlipXY. Rotation must be specified with Rotate or srcRotate instead. Received: " + flip.ToString());
        }
The documentation for this class was generated from the following file:
C:/Users/Administrator/Documents/resizer/Core/Util/Utils.cs