ImageResizer: ImageResizer.Configuration.PluginConfig Class Reference
ImageResizer.Configuration.PluginConfig Class Reference
Provides thread-safe access to plugin addition, removal, and querying methods.
Public Member Functions
PluginConfig (Config c)
Creates a new plugin config section, attached to the specified parent.
void LoadPlugins ()
Processes the <plugins> section if they are not already loaded. Thread safe. Only executes once.
IList< IPlugin > GetPlugins (Type type)
Returns the subset of installed plugins which implement the specified type or interface.
IList< T > GetAll< T > ()
Returns all registered instances of the specified plugins.
bool HasPlugin (Type type)
Returns true if at least one plugin of the specified type is registered.
bool Has< T > ()
Returns true if 1 or more instances of the type are registered.
T Get< T > ()
Returns the first registerd instance of the specified plugin. For IMultiInstancePlugins, use GetAll()
T GetOrInstall< T > ()
Returns the first registered instance of the specified plugin, or creates a new instance if the plugin isn't installed.
T GetOrInstall< T > (T newInstance)
Returns the first registered instance of the specified plugin, or installs the given instance instead, then re-tries the query.
IPlugin Install (IPlugin plugin)
Installs the specified plugin, returning the plugin instance. Convenience method, same as plugin.Install(Config.Current).
bool Uninstall (IPlugin plugin)
Attempts uninstallation of the specified plugin, returning true if successful. Convenience method, same as plugin.Uninstall(Config.Current).
delegate void LoggingAvaialbleEvent (ILogManager logger)
IEncoder GetEncoder (ResizeSettings settings, object original)
Returns an instance of the first encoder that claims to be able to handle the specified settings. Returns null if no encoders are available.
Type FindPluginType (string searchName)
Searches all loaded assemblies for the specified type, applying rules and prefixes to resolve the namespace and assembly. Returns null if it could not find the type, and logs an issue.
void remove_plugin (object plugin)
For use only by plugins during .Uninstall. Removes the specified plugin from AllPlugins, QuerystringPlugins, CachingSystems, ImageEncoders, and ImageBuiderExtensions, based on which interfaces the instance implements. Plugins may register event handlers and modify settings - thus you should use the plugin's method to uninstall them vs. using this method.
void add_plugin (IPlugin plugin)
Only for use by plugins during IPlugin.Install. Call Plugin.Install instead of this method, since plugins often must perform other initialization actions. Adds the specified plugin to AllPlugins, QuerystringPlugins, CachingSystems, ImageEncoders, and ImageBuiderExtensions, based on which interfaces the instance implements. For ICache and IEncoder, the plugin is inserted at the beginning of CachingSystems and ImageEncoders respectively. To reiterate, plugins may register event handlers and modify settings - thus you should use the plugin's method to uninstall them vs. using this method. Will not register a plugin that is already installed, unless it implementes IMultiInstancePlugin.
void RemoveAll ()
Removes all plugins, of every kind. Logs any errors encountered. (Not all plugins support uninstallation)
override IEnumerable< IIssue > GetIssues ()
Returns a copy of the list of reported issues.
Public Attributes
LoggingAvaialbleEvent LoggingAvailable
Protected Member Functions
void loadPluginsInternal ()
Not thread safe. Performs actual work.
void remove_plugins_by_name (string name)
void add_plugin_by_name (string name, NameValueCollection args)
void clear_plugins_by_type (string type)
List< string > GetOptimizedAssemblyList (string assemblyName, string pluginName)
This is called to get a sorted list of plugins based on their likelyhood of having the plugin.
IPlugin CreatePluginByName (string name, NameValueCollection args)
IPlugin CreatePluginByType (Type t, NameValueCollection args)
Protected Attributes
NativeDependencyManager ndeps = new NativeDependencyManager()
Config c
volatile bool _pluginsLoaded = false
object _loadPluginsSync = new object()
SafeList< ICurrentConfigProvider > configProviders = null
SafeList< BuilderExtension > imageBuilderExtensions = null
SafeList< IEncoder > imageEncoders = null
SafeList< ICache > cachingSystems = null
SafeList< IQuerystringPlugin > querystringPlugins = null
SafeList< IFileExtensionPlugin > fileExtensionPlugins = null
SafeList< IVirtualImageProvider > virtualProviderPlugins = null
SafeList< ISettingsModifier > settingsModifierPlugins = null
SafeList< IPlugin > allPlugins = null
ILogManager _logManager = null
Properties
bool PluginsLoaded [get]
Returns true if the <plugins> section has been processed.
SafeList< ICurrentConfigProvider > ConfigProviders [get]
Currently registered ICurrentConfigProviders.
SafeList< BuilderExtension > ImageBuilderExtensions [get]
Currently registered set of ImageBuilderExtensions.
SafeList< IEncoder > ImageEncoders [get]
Currently registered IEncoders.
SafeList< ICache > CachingSystems [get]
Currently registered ICache instances.
SafeList< IQuerystringPlugin > QuerystringPlugins [get]
Plugins which accept querystring arguments are registered here.
SafeList< IFileExtensionPlugin > FileExtensionPlugins [get]
Plugins which accept new file extensions (in the url) are registered here.
SafeList< IVirtualImageProvider > VirtualProviderPlugins [get]
Plugins which provide virtual files are registered here.
SafeList< ISettingsModifier > SettingsModifierPlugins [get]
Plugins which modify image processing settings.
SafeList< IPlugin > AllPlugins [get]
All plugins should be registered here. Used for diagnostic purposes.
IEncoderProvider EncoderProvider [get]
ILogManager LogManager [get, set]
Returns the most recently registered Logging plugin, or null.
Detailed Description
Provides thread-safe access to plugin addition, removal, and querying methods.
Definition at line 24 of file PluginConfig.cs.
Constructor & Destructor Documentation
ImageResizer.Configuration.PluginConfig.PluginConfig (Config c) [inline]
Creates a new plugin config section, attached to the specified parent.
Parameters:
c
Definition at line 35 of file PluginConfig.cs.
                                      : base("Plugins"){
            this.c = c;
            imageBuilderExtensions = new SafeList<BuilderExtension>();
            imageEncoders = new SafeList<IEncoder>();
            cachingSystems = new SafeList<ICache>();
            querystringPlugins = new SafeList<IQuerystringPlugin>();
            fileExtensionPlugins = new SafeList<IFileExtensionPlugin>();
            allPlugins = new SafeList<IPlugin>();
            virtualProviderPlugins = new SafeList<IVirtualImageProvider>();
            settingsModifierPlugins = new SafeList<ISettingsModifier>();
            configProviders = new SafeList<ICurrentConfigProvider>();
        }
Member Function Documentation
void ImageResizer.Configuration.PluginConfig.add_plugin (IPlugin plugin) [inline]
Only for use by plugins during IPlugin.Install. Call Plugin.Install instead of this method, since plugins often must perform other initialization actions. Adds the specified plugin to AllPlugins, QuerystringPlugins, CachingSystems, ImageEncoders, and ImageBuiderExtensions, based on which interfaces the instance implements. For ICache and IEncoder, the plugin is inserted at the beginning of CachingSystems and ImageEncoders respectively. To reiterate, plugins may register event handlers and modify settings - thus you should use the plugin's method to uninstall them vs. using this method. Will not register a plugin that is already installed, unless it implementes IMultiInstancePlugin.
Parameters:
plugin
Definition at line 531 of file PluginConfig.cs.
Referenced by ImageResizer.Plugins.WebPEncoder.WebPEncoderPlugin.Install(), ImageResizer.Plugins.Basic.ImageHandlerSyntax.Install(), ImageResizer.Plugins.PsdComposer.PsdComposerPlugin.Install(), ImageResizer.Plugins.Basic.Trial.Install(), ImageResizer.Plugins.Basic.VirtualFolder.Install(), ImageResizer.Plugins.DiskCache.DiskCache.Install(), ImageResizer.Plugins.PdfRenderer.PdfRendererPlugin.Install(), ImageResizer.Licensing.LicenseVerifier.Install(), and ImageResizer.Licensing.LicenseStore.Install().
{
            if (!(plugin is IMultiInstancePlugin) && HasPlugin(plugin.GetType())) {
                AcceptIssue(new Issue("An instance of the specified plugin (" + plugin.GetType().ToString() + ") has already been registered.",
                                    "The plugin should implement IMultiInstancePlugin to support multiple instances.", IssueSeverity.Error));
                return;
            }
            AllPlugins.Add(plugin);
            if (plugin is IQuerystringPlugin) QuerystringPlugins.Add(plugin as IQuerystringPlugin);
            if (plugin is IFileExtensionPlugin) FileExtensionPlugins.Add(plugin as IFileExtensionPlugin);
            if (plugin is ICache) CachingSystems.AddFirst(plugin as ICache);
            if (plugin is IEncoder) ImageEncoders.AddFirst(plugin as IEncoder);
            if (plugin is BuilderExtension) ImageBuilderExtensions.Add(plugin as BuilderExtension);
            if (plugin is IVirtualImageProvider) VirtualProviderPlugins.Add(plugin as IVirtualImageProvider);
            if (plugin is ISettingsModifier) SettingsModifierPlugins.Add(plugin as ISettingsModifier);
            if (plugin is ICurrentConfigProvider) ConfigProviders.Add(plugin as ICurrentConfigProvider);
            if (plugin is ILogManager) LogManager = plugin as ILogManager;
        }
Type ImageResizer.Configuration.PluginConfig.FindPluginType (string searchName) [inline]
Searches all loaded assemblies for the specified type, applying rules and prefixes to resolve the namespace and assembly. Returns null if it could not find the type, and logs an issue.
Parameters:
searchName
Returns:
Definition at line 366 of file PluginConfig.cs.
{
            Type t = null;
            int commaAt = searchName.IndexOf(',');
            int dotAt = searchName.IndexOf('.');
            //If there is a dot or period, try the exact name first.
            if (dotAt > -1 || commaAt > -1)
                t = Type.GetType(searchName, false, true);
            if (t != null) return t;
            //Split the name and assembly apart
            string assembly = commaAt > -1 ? searchName.Substring(commaAt) : null;
            string name = commaAt > -1 ? searchName.Substring(0, commaAt) : searchName;
            //Without the assembly specified, does it still have a name?
            bool hasDot = name.IndexOf('.') > -1;
            List<string> alternateNames = new List<string>();
            //ImageResizer.Plugins.Basic.DefaultEncoder
            if (hasDot) alternateNames.Add(name);
            //DefaultEncoder, NoCache, etc.
            alternateNames.Add("ImageResizer.Plugins.Basic." + name.TrimStart('.'));
            //Apr4-2012 - Deleted, never used: alternateNames.Add("ImageResizer.Plugins.Pro." + name.TrimStart('.'));
            //AnimatedGifs
            if (!hasDot) alternateNames.Add("ImageResizer.Plugins." + name.Trim('.') + "." + name.Trim('.') + "Plugin");
            //AnimatedGifsPlugin
            if (!hasDot && name.EndsWith("Plugin"))
                alternateNames.Add("ImageResizer.Plugins." + name.Substring(0, name.Length - 6).Trim('.') + "." + name.Trim('.'));
            //Apr4-2012 - Deleted, never used: //Basic.DefaultEncoder
            //Apr4-2012 - Deleted, never used: alternateNames.Add("ImageResizer.Plugins." + name.TrimStart('.'));
            //For the deprecated convention of naming the plugin namespace and class the same.
            if (!hasDot) alternateNames.Add("ImageResizer.Plugins." + name.Trim('.') + "." + name.Trim('.'));
            //Apr4-2012 - Deleted, never used: //Plugins.Basic.DefaultEncoder
            //Apr4-2012 - Deleted, never used: alternateNames.Add("ImageResizer." + name.TrimStart('.'));
            //PluginWithNoNamespace
            if (!hasDot) alternateNames.Add(name);
            //Get a list of assemblies, sorted by likelyhood of a match
            List<string> assemblies = GetOptimizedAssemblyList(assembly,name);
            //Now multiply
            List<string> qualifiedNames = new List<string>(assemblies.Count * alternateNames.Count);
            //For each assembly, try each namespace-qualified class name.
            foreach (string assemblyName in assemblies) {
                foreach (string className in alternateNames)
                    qualifiedNames.Add(className + assemblyName);
            }
            try {
                //Now, try them all.
                foreach (string s in qualifiedNames) {
                    Debug.WriteLine("Trying " + s);
                    t = Type.GetType(s, false, true);
                    if (t != null) {
                        Debug.WriteLine("Success!");
                        return t;
                    }
                }
            } catch (System.Security.SecurityException sx) {
                this.AcceptIssue(new Issue("Failed to load plugin \"" + searchName + "\" due to ASP.NET trust configuration. ",
                                "You may need to increase the trust level for this plugin to load properly. Error details: \n" +
                                sx.Message + "\n" + sx.StackTrace, IssueSeverity.Error));
                return null;
            }
            //Ok, time to log problem.
            if (t == null) {
                StringBuilder attempts = new StringBuilder();
                foreach (string s in qualifiedNames)
                    attempts.Append(", \"" + s + "\"");
                this.AcceptIssue(new Issue("Failed to load plugin by name \"" + searchName + "\"",
                    "Verify the plugin DLL is located in /bin, and that the name is spelled correctly. \n" +
                    "Attempted using \"" + searchName + "\"" + attempts.ToString() + ".", IssueSeverity.ConfigurationError));
            }
            return t;
        }
T ImageResizer.Configuration.PluginConfig.Get< T > () [inline]
Returns the first registerd instance of the specified plugin. For IMultiInstancePlugins, use GetAll()
Template Parameters:
T
Returns:
Definition at line 145 of file PluginConfig.cs.
{
            Type t = typeof(T);
            foreach (IPlugin p in AllPlugins)
                if (t.IsAssignableFrom(p.GetType())) //Like instance of. Can be a subclass
                    return (T)p;
            return default(T);
        }
IList<T> ImageResizer.Configuration.PluginConfig.GetAll< T > () [inline]
Returns all registered instances of the specified plugins.
Template Parameters:
T
Returns:
Definition at line 109 of file PluginConfig.cs.
{
            List<T> results = new List<T>();
            Type t = typeof(T);
            foreach (IPlugin p in AllPlugins)
                if (t.IsAssignableFrom(p.GetType())) //Like instance of. Can be a subclass
                    results.Add((T)p);
            return results;
        }
IEncoder ImageResizer.Configuration.PluginConfig.GetEncoder (ResizeSettings settings, object original) [inline]
Returns an instance of the first encoder that claims to be able to handle the specified settings. Returns null if no encoders are available.
Parameters:
settings Request settings, like format, quality, colors, dither, etc.
original May be a Drawing.Image instance, a path, or null. To provide both, set Image.tag to the path. Helps the encoder detect the original format if the format was not specified. May also be used for palette generation hinting by some encoders.
Returns:
Implements ImageResizer.Encoding.IEncoderProvider.
Definition at line 284 of file PluginConfig.cs.
{
            foreach (IEncoder e in this.ImageEncoders) {
                IEncoder result = e.CreateIfSuitable(settings, original);
                if (result != null) return result;
            }
            return null;
        }
override IEnumerable<IIssue> ImageResizer.Configuration.PluginConfig.GetIssues () [inline, virtual]
Returns a copy of the list of reported issues.
Returns:
Reimplemented from ImageResizer.Configuration.Issues.IssueSink.
Definition at line 579 of file PluginConfig.cs.
{
            List<IIssue> issues = new List<IIssue>(base.GetIssues());
            //Verify all plugins are registered as IPlugins also.
            //Verify there is something other than NoCache registered
            if (c.Plugins.CachingSystems.First is ImageResizer.Plugins.Basic.NoCache)
                issues.Add(new Issue("NoCache is only for development usage, and cannot scale to production use.", "Add DiskCache or CloudFront for production use", IssueSeverity.Warning));
            //Verify NoCache is registered
            if (!c.Plugins.Has<ImageResizer.Plugins.Basic.NoCache>())
                issues.Add(new Issue("NoCache should not be removed from the plugins collection.",
                    "Simply add the new ICache plugin later for it to take precedence. NoCache is still required as a fallback by most caching plugins.",
                     IssueSeverity.Error));
            if (c.Plugins.ImageEncoders.First == null)
                issues.Add(new Issue("No encoders are registered! Without an image encoder, the pipeline cannot function.", IssueSeverity.Error));
            issues.AddRange(ndeps.GetIssues());
            return issues;
        }
List<string> ImageResizer.Configuration.PluginConfig.GetOptimizedAssemblyList (string assemblyName, string pluginName) [inline, protected]
This is called to get a sorted list of plugins based on their likelyhood of having the plugin.
Parameters:
assemblyName
pluginName
Returns:
Definition at line 335 of file PluginConfig.cs.
{
            List<string> assemblies = new List<string>();
            //1) If an assembly was specified, search it first
            if (assemblyName != null) assemblies.Add(assemblyName);
            //2) Follow by searching the Core, the currently executing assembly
            assemblies.Add(""); // Defaults to current assembly
            //3) Add ImageResizer.Plugins.X if it has no dot.
            if (!pluginName.Contains(".")) assemblies.Add("ImageResizer.Plugins." + pluginName);
            //4) Next, add all assemblies that have "ImageResizer" in their name
            List<string> otherAssemblies = new List<string>();
            //Add ImageResizer-related assemblies first
            foreach (Assembly a in AppDomain.CurrentDomain.GetAssemblies()) {// AppDomain.CurrentDomain.GetAssemblies()
                string aname = a.FullName;
                if (aname.IndexOf("ImageResizer", StringComparison.OrdinalIgnoreCase) > -1) assemblies.Add(", " + aname);
                else
                    otherAssemblies.Add(", " + aname);
            }
            //5) Last, add all remaining assemblies
            assemblies.AddRange(otherAssemblies);
            return assemblies;
        }
T ImageResizer.Configuration.PluginConfig.GetOrInstall< T > () [inline]
Returns the first registered instance of the specified plugin, or creates a new instance if the plugin isn't installed.
Template Parameters:
T
Returns:
Type Constraints
T : IPlugin
T : new()
Definition at line 158 of file PluginConfig.cs.
                                           : IPlugin, new() {
            T instance = Get<T>();
            if (instance != null) return instance;
            new T().Install(this.c);
            return Get<T>();
        }
T ImageResizer.Configuration.PluginConfig.GetOrInstall< T > (T newInstance) [inline]
Returns the first registered instance of the specified plugin, or installs the given instance instead, then re-tries the query.
Template Parameters:
T
Parameters:
newInstance
Returns:
Type Constraints
T : IPlugin
Definition at line 173 of file PluginConfig.cs.
                                                        : IPlugin {
            T instance = Get<T>();
            if (instance != null) return instance;
            //Our instance may not get installed if there is a duplicate already
            newInstance.Install(this.c);
            return Get<T>();
        }
IList<IPlugin> ImageResizer.Configuration.PluginConfig.GetPlugins (Type type) [inline]
Returns the subset of installed plugins which implement the specified type or interface.
Parameters:
type
Returns:
Definition at line 97 of file PluginConfig.cs.
{
            List<IPlugin> results = new List<IPlugin>();
            foreach (IPlugin p in AllPlugins)
                if (type.IsAssignableFrom(p.GetType())) //Like instance of. Can be a subclass
                    results.Add(p);
            return results;
        }
bool ImageResizer.Configuration.PluginConfig.Has< T > () [inline]
Returns true if 1 or more instances of the type are registered.
Template Parameters:
T
Returns:
Definition at line 135 of file PluginConfig.cs.
{
            return Comparer<T>.Default.Compare(Get<T>(), default(T)) != 0;
        }
bool ImageResizer.Configuration.PluginConfig.HasPlugin (Type type) [inline]
Returns true if at least one plugin of the specified type is registered.
Parameters:
type
Returns:
Definition at line 123 of file PluginConfig.cs.
{
            foreach (IPlugin p in AllPlugins)
                if (type.IsAssignableFrom(p.GetType())) //Like instance of. Can be a subclass
                    return true;
            return false;
        }
IPlugin ImageResizer.Configuration.PluginConfig.Install (IPlugin plugin) [inline]
Installs the specified plugin, returning the plugin instance. Convenience method, same as plugin.Install(Config.Current).
Parameters:
plugin
Returns:
Definition at line 190 of file PluginConfig.cs.
{
            return plugin.Install(this.c);
        }
void ImageResizer.Configuration.PluginConfig.LoadPlugins () [inline]
Processes the <plugins> section if they are not already loaded. Thread safe. Only executes once.
Definition at line 56 of file PluginConfig.cs.
{
            lock (_loadPluginsSync) {
                if (_pluginsLoaded) return;
                loadPluginsInternal();
                _pluginsLoaded = true;
            }
        }
void ImageResizer.Configuration.PluginConfig.loadPluginsInternal () [inline, protected]
Not thread safe. Performs actual work.
Definition at line 75 of file PluginConfig.cs.
{
            Node plugins = c.getNode("plugins");
            if (plugins == null) return;
            foreach (Node n in plugins.Children) {
                if (n.Name.Equals("add", StringComparison.OrdinalIgnoreCase)) {
                    add_plugin_by_name(n["name"],(n.Attrs.Count > 1) ? n.Attrs : null);
                } else if (n.Name.Equals("remove", StringComparison.OrdinalIgnoreCase))
                    remove_plugins_by_name(n["name"]);
                else if (n.Name.Equals("clear", StringComparison.OrdinalIgnoreCase))
                    clear_plugins_by_type(n["type"]);
                else {
                    this.AcceptIssue(new Issue("Plugins", "Unexpected element <" + n.Name + "> in <plugins></plugins>.",
                                                "Element XML: " + n.ToXmlElement().OuterXml, IssueSeverity.Warning));
                }
            }
        }
void ImageResizer.Configuration.PluginConfig.remove_plugin (object plugin) [inline]
For use only by plugins during .Uninstall. Removes the specified plugin from AllPlugins, QuerystringPlugins, CachingSystems, ImageEncoders, and ImageBuiderExtensions, based on which interfaces the instance implements. Plugins may register event handlers and modify settings - thus you should use the plugin's method to uninstall them vs. using this method.
Parameters:
plugin
Definition at line 510 of file PluginConfig.cs.
Referenced by ImageResizer.Plugins.WebPEncoder.WebPEncoderPlugin.Uninstall(), ImageResizer.Plugins.Basic.SizeLimiting.Uninstall(), ImageResizer.Plugins.PsdComposer.PsdComposerPlugin.Uninstall(), ImageResizer.Plugins.Basic.VirtualFolder.Uninstall(), ImageResizer.Plugins.DiskCache.DiskCache.Uninstall(), and ImageResizer.Plugins.PdfRenderer.PdfRendererPlugin.Uninstall().
{
            if (plugin is IPlugin) AllPlugins.Remove(plugin as IPlugin);
            if (plugin is IQuerystringPlugin) QuerystringPlugins.Remove(plugin as IQuerystringPlugin);
            if (plugin is IFileExtensionPlugin) FileExtensionPlugins.Remove(plugin as IFileExtensionPlugin);
            if (plugin is ICache) CachingSystems.Remove(plugin as ICache);
            if (plugin is IEncoder) ImageEncoders.Remove(plugin as IEncoder);
            if (plugin is BuilderExtension) ImageBuilderExtensions.Remove(plugin as BuilderExtension);
            if (plugin is IVirtualImageProvider) VirtualProviderPlugins.Remove(plugin as IVirtualImageProvider);
            if (plugin is ISettingsModifier) SettingsModifierPlugins.Remove(plugin as ISettingsModifier);
            if (plugin is ICurrentConfigProvider) ConfigProviders.Remove(plugin as ICurrentConfigProvider);
            if (plugin is ILogManager && LogManager == plugin) LogManager = null;
        }
void ImageResizer.Configuration.PluginConfig.RemoveAll () [inline]
Removes all plugins, of every kind. Logs any errors encountered. (Not all plugins support uninstallation)
Definition at line 556 of file PluginConfig.cs.
{
            //Follow uninstall protocol
            foreach (IPlugin p in AllPlugins)
                if (!p.Uninstall(c))
                    this.AcceptIssue(new Issue("Uninstall of " + p.ToString() + " reported failure.", IssueSeverity.Error));
            IList[] collections = new IList[]{AllPlugins.GetCollection(),QuerystringPlugins.GetCollection(),FileExtensionPlugins.GetCollection()
                                                ,CachingSystems.GetCollection(),ImageEncoders.GetCollection(),ImageBuilderExtensions.GetCollection()};
            //Then check all collections, logging an issue if they aren't empty.
            foreach(IList coll in collections){
                if (coll.Count > 0){
                    string items = "";
                    foreach(object item in coll)
                        items += item.ToString() + ", ";
                    this.AcceptIssue(new Issue("Collection " + coll.ToString() + " was not empty after RemoveAllPlugins() executed!",
                                        "Remaining items: " + items, IssueSeverity.Error));
                }
            }
        }
bool ImageResizer.Configuration.PluginConfig.Uninstall (IPlugin plugin) [inline]
Attempts uninstallation of the specified plugin, returning true if successful. Convenience method, same as plugin.Uninstall(Config.Current).
Parameters:
plugin
Returns:
Definition at line 200 of file PluginConfig.cs.
{
            return plugin.Uninstall(this.c);
        }
Property Documentation
SafeList<IPlugin> ImageResizer.Configuration.PluginConfig.AllPlugins [get]
All plugins should be registered here. Used for diagnostic purposes.
Definition at line 261 of file PluginConfig.cs.
Referenced by ImageResizer.Plugins.Basic.SizeLimiting.Install().
SafeList<ICache> ImageResizer.Configuration.PluginConfig.CachingSystems [get]
Currently registered ICache instances.
Definition at line 228 of file PluginConfig.cs.
Referenced by ImageResizer.Configuration.PipelineConfig.GetCachingSystem().
SafeList<ICurrentConfigProvider> ImageResizer.Configuration.PluginConfig.ConfigProviders [get]
Currently registered ICurrentConfigProviders.
Definition at line 209 of file PluginConfig.cs.
SafeList<IFileExtensionPlugin> ImageResizer.Configuration.PluginConfig.FileExtensionPlugins [get]
Plugins which accept new file extensions (in the url) are registered here.
Definition at line 241 of file PluginConfig.cs.
Referenced by ImageResizer.Configuration.PipelineConfig._cacheUrlData().
SafeList<BuilderExtension> ImageResizer.Configuration.PluginConfig.ImageBuilderExtensions [get]
Currently registered set of ImageBuilderExtensions.
Definition at line 216 of file PluginConfig.cs.
Referenced by ImageResizer.Plugins.Basic.SizeLimiting.Install().
SafeList<IEncoder> ImageResizer.Configuration.PluginConfig.ImageEncoders [get]
Currently registered IEncoders.
Definition at line 222 of file PluginConfig.cs.
ILogManager ImageResizer.Configuration.PluginConfig.LogManager [get, set]
Returns the most recently registered Logging plugin, or null.
Definition at line 270 of file PluginConfig.cs.
Referenced by ImageResizer.Plugins.DiskCache.DiskCache.Install().
bool ImageResizer.Configuration.PluginConfig.PluginsLoaded [get]
Returns true if the <plugins> section has been processed.
Definition at line 66 of file PluginConfig.cs.
SafeList<IQuerystringPlugin> ImageResizer.Configuration.PluginConfig.QuerystringPlugins [get]
Plugins which accept querystring arguments are registered here.
Definition at line 234 of file PluginConfig.cs.
Referenced by ImageResizer.Configuration.PipelineConfig._cacheUrlData().
SafeList<ISettingsModifier> ImageResizer.Configuration.PluginConfig.SettingsModifierPlugins [get]
Plugins which modify image processing settings.
Definition at line 254 of file PluginConfig.cs.
Referenced by ImageResizer.Configuration.PipelineConfig.Modify().
SafeList<IVirtualImageProvider> ImageResizer.Configuration.PluginConfig.VirtualProviderPlugins [get]
Plugins which provide virtual files are registered here.
Definition at line 248 of file PluginConfig.cs.
Referenced by ImageResizer.Configuration.PipelineConfig.FileExists(), and ImageResizer.Configuration.PipelineConfig.GetFile().
The documentation for this class was generated from the following file:
C:/Users/Administrator/Documents/resizer/Core/Configuration/PluginConfig.cs