ImageResizer: ImageResizer.Plugins.PsdComposer.MemCachedFile Class Reference
ImageResizer.Plugins.PsdComposer.MemCachedFile Class Reference
Caches a file in memory using the asp.net Cache object, while exposing methods for adding subkeys that invalidate along with the file if the source file is changed.
Public Member Functions
object GetSubkey (string subkey)
Remember, the object returned here may be accessed by multiple threads at the same time! No modifications!
void SetSubkey (string subkey, object item)
Stream GetStream ()
Wraps the byte array in a read-only stream.
Static Public Member Functions
static MemCachedFile GetCachedVirtualFile (string path, IVirtualImageProvider provider, NameValueCollection queryString)
Detailed Description
Caches a file in memory using the asp.net Cache object, while exposing methods for adding subkeys that invalidate along with the file if the source file is changed.
Definition at line 18 of file MemCachedFile.cs.
Member Function Documentation
Stream ImageResizer.Plugins.PsdComposer.MemCachedFile.GetStream () [inline]
Wraps the byte array in a read-only stream.
Returns:
Definition at line 52 of file MemCachedFile.cs.
Referenced by ImageResizer.Plugins.PsdComposer.PsdComposerPlugin.ComposeBitmap(), and ImageResizer.Plugins.PsdComposer.PsdComposerPlugin.GetFileMetadata().
        {
            return new MemoryStream(data,false);
        }
object ImageResizer.Plugins.PsdComposer.MemCachedFile.GetSubkey (string subkey) [inline]
Remember, the object returned here may be accessed by multiple threads at the same time! No modifications!
Parameters:
subkey
Returns:
Definition at line 31 of file MemCachedFile.cs.
Referenced by ImageResizer.Plugins.PsdComposer.PsdComposerPlugin.GetFileMetadata().
        {
            lock (subkey_syncobj)
            {
                if (!subkeys.ContainsKey(subkey)) return null;
                return subkeys[subkey];
            }
        }
The documentation for this class was generated from the following file:
C:/Users/Administrator/Documents/resizer/Plugins/PsdComposer/MemCachedFile.cs