ImageResizer: ImageResizer.Configuration.Logging.ILogger Interface Reference
ImageResizer.Configuration.Logging.ILogger Interface Reference
Public Member Functions
void Log (string level, string message)
Writes the diagnostic message at the specified level.
void Trace (string message)
Writes the diagnostic message at the Trace level.
void Trace (string message, params object[] args)
void Debug (string message)
Writes the diagnostic message at the Debug level.
void Debug (string message, params object[] args)
void Info (string message)
Writes the diagnostic message at the Info level.
void Info (string message, params object[] args)
void Warn (string message)
Writes the diagnostic message at the Warn level.
void Warn (string message, params object[] args)
void Error (string message)
Writes the diagnostic message at the Error level.
void Error (string message, params object[] args)
void Fatal (string message)
Writes the diagnostic message at the Fatal level.
void Fatal (string message, params object[] args)
bool IsEnabled (string level)
Checks if the specified log level is enabled.
Properties
bool IsTraceEnabled [get]
Gets a value indicating whether the Trace level is enabled.
bool IsDebugEnabled [get]
Gets a value indicating whether the Debug level is enabled.
bool IsInfoEnabled [get]
Gets a value indicating whether the Info level is enabled.
bool IsWarnEnabled [get]
Gets a value indicating whether the Warn level is enabled.
bool IsErrorEnabled [get]
Gets a value indicating whether the Error level is enabled.
bool IsFatalEnabled [get]
Gets a value indicating whether the Fatal level is enabled.
string LoggerName [get, set]
Gets or sets the logger name.
Detailed Description
Definition at line 8 of file ILogger.cs.
Member Function Documentation
void ImageResizer.Configuration.Logging.ILogger.Debug (string message)
Writes the diagnostic message at the Debug level.
Parameters:
message A to be written.
Implemented in ImageResizer.Plugins.Logging.LoggerProxy.
Referenced by ImageResizer.Plugins.DiskCache.WebConfigWriter._checkWebConfig().
void ImageResizer.Configuration.Logging.ILogger.Error (string message)
Writes the diagnostic message at the Error level.
Parameters:
message A to be written.
Implemented in ImageResizer.Plugins.Logging.LoggerProxy.
Referenced by ImageResizer.Plugins.DiskCache.CustomDiskCache.GetCachedFile().
void ImageResizer.Configuration.Logging.ILogger.Fatal (string message)
Writes the diagnostic message at the Fatal level.
Parameters:
message A to be written.
Implemented in ImageResizer.Plugins.Logging.LoggerProxy.
void ImageResizer.Configuration.Logging.ILogger.Info (string message)
Writes the diagnostic message at the Info level.
Parameters:
message A to be written.
Implemented in ImageResizer.Plugins.Logging.LoggerProxy.
Referenced by ImageResizer.Plugins.DiskCache.WebConfigWriter._checkWebConfig().
bool ImageResizer.Configuration.Logging.ILogger.IsEnabled (string level)
Checks if the specified log level is enabled.
Parameters:
level The log level.
Returns:
A value indicating whether the specified log level is enabled.
Implemented in ImageResizer.Plugins.Logging.LoggerProxy.
void ImageResizer.Configuration.Logging.ILogger.Log (string level, string message)
Writes the diagnostic message at the specified level.
Parameters:
level The log level.
message A to be written.
Implemented in ImageResizer.Plugins.Logging.LoggerProxy.
void ImageResizer.Configuration.Logging.ILogger.Trace (string message)
Writes the diagnostic message at the Trace level.
Parameters:
message A to be written.
Implemented in ImageResizer.Plugins.Logging.LoggerProxy.
Referenced by ImageResizer.Plugins.DiskCache.CustomDiskCache.GetCachedFile().
void ImageResizer.Configuration.Logging.ILogger.Warn (string message)
Writes the diagnostic message at the Warn level.
Parameters:
message A to be written.
Implemented in ImageResizer.Plugins.Logging.LoggerProxy.
Referenced by ImageResizer.Plugins.DiskCache.CustomDiskCache.GetCachedFile().
Property Documentation
bool ImageResizer.Configuration.Logging.ILogger.IsDebugEnabled [get]
Gets a value indicating whether the Debug level is enabled.
Implemented in ImageResizer.Plugins.Logging.LoggerProxy.
Definition at line 74 of file ILogger.cs.
bool ImageResizer.Configuration.Logging.ILogger.IsErrorEnabled [get]
Gets a value indicating whether the Error level is enabled.
Implemented in ImageResizer.Plugins.Logging.LoggerProxy.
Definition at line 89 of file ILogger.cs.
bool ImageResizer.Configuration.Logging.ILogger.IsFatalEnabled [get]
Gets a value indicating whether the Fatal level is enabled.
Implemented in ImageResizer.Plugins.Logging.LoggerProxy.
Definition at line 94 of file ILogger.cs.
bool ImageResizer.Configuration.Logging.ILogger.IsInfoEnabled [get]
Gets a value indicating whether the Info level is enabled.
Implemented in ImageResizer.Plugins.Logging.LoggerProxy.
Definition at line 79 of file ILogger.cs.
bool ImageResizer.Configuration.Logging.ILogger.IsTraceEnabled [get]
Gets a value indicating whether the Trace level is enabled.
Implemented in ImageResizer.Plugins.Logging.LoggerProxy.
Definition at line 68 of file ILogger.cs.
bool ImageResizer.Configuration.Logging.ILogger.IsWarnEnabled [get]
Gets a value indicating whether the Warn level is enabled.
Implemented in ImageResizer.Plugins.Logging.LoggerProxy.
Definition at line 84 of file ILogger.cs.
string ImageResizer.Configuration.Logging.ILogger.LoggerName [get, set]
Gets or sets the logger name.
Implemented in ImageResizer.Plugins.Logging.LoggerProxy.
Definition at line 99 of file ILogger.cs.
The documentation for this interface was generated from the following file:
C:/Users/Administrator/Documents/resizer/Core/Configuration/Logging/ILogger.cs