ImageResizer: ImageResizer.Plugins.IPlugin Interface Reference
ImageResizer.Plugins.IPlugin Interface Reference
All plugins must implement this. Enables web.config addition and removal.
Inherited by ImageResizer.Licensing.LicenseStore, ImageResizer.Plugins.AdvancedFilters.AdvancedFilters, ImageResizer.Plugins.AnimatedGifs.AnimatedGifs, ImageResizer.Plugins.AzureReader2.AzureReader2Plugin, ImageResizer.Plugins.AzureReader.AzureReader, ImageResizer.Plugins.Basic.AutoRotate, ImageResizer.Plugins.Basic.ClientCache, ImageResizer.Plugins.Basic.DefaultEncoder, ImageResizer.Plugins.Basic.DefaultSettings, ImageResizer.Plugins.Basic.Diagnostic, ImageResizer.Plugins.Basic.DropShadow, ImageResizer.Plugins.Basic.FolderResizeSyntax, ImageResizer.Plugins.Basic.Gradient, ImageResizer.Plugins.Basic.IEPngFix, ImageResizer.Plugins.Basic.Image404, ImageResizer.Plugins.Basic.ImageHandlerSyntax, ImageResizer.Plugins.Basic.ImageInfoAPI, ImageResizer.Plugins.Basic.NoCache, ImageResizer.Plugins.Basic.Presets, ImageResizer.Plugins.Basic.SizeLimiting, ImageResizer.Plugins.Basic.SpeedOrQuality, ImageResizer.Plugins.Basic.Trial, ImageResizer.Plugins.Basic.VirtualFolder, ImageResizer.Plugins.CloudFront.CloudFrontPlugin, ImageResizer.Plugins.CropAround.CropAroundPlugin, ImageResizer.Plugins.DiskCache.DiskCache, ImageResizer.Plugins.Encrypted.EncryptedPlugin, ImageResizer.Plugins.Faces.FacesPlugin, ImageResizer.Plugins.FreeImageBuilder.FreeImageBuilderPlugin, ImageResizer.Plugins.FreeImageDecoder.FreeImageDecoderPlugin, ImageResizer.Plugins.FreeImageEncoder.FreeImageEncoderPlugin, ImageResizer.Plugins.FreeImageScaling.FreeImageScalingPlugin, ImageResizer.Plugins.ILicenseService, ImageResizer.Plugins.ILicenseStore, ImageResizer.Plugins.Logging.LoggingPlugin, ImageResizer.Plugins.MemCache.MemCachePlugin, ImageResizer.Plugins.MongoReader.MongoReaderPlugin, ImageResizer.Plugins.MvcRoutingShim.MvcRoutingShimPlugin, ImageResizer.Plugins.PdfRenderer.PdfRendererPlugin, ImageResizer.Plugins.PrettyGifs.PrettyGifs, ImageResizer.Plugins.PsdComposer.PsdComposerPlugin, ImageResizer.Plugins.PsdReader.PsdReader, ImageResizer.Plugins.RedEye.RedEyePlugin, ImageResizer.Plugins.RemoteReader.RemoteReaderPlugin, ImageResizer.Plugins.S3Reader.S3Reader, ImageResizer.Plugins.SeamCarving.SeamCarvingPlugin, ImageResizer.Plugins.SimpleFilters.SimpleFilters, ImageResizer.Plugins.SourceMemCache.SourceMemCachePlugin, ImageResizer.Plugins.SqlReader.SqlReaderPlugin, ImageResizer.Plugins.TinyCache.TinyCachePlugin, ImageResizer.Plugins.Watermark.WatermarkPlugin, ImageResizer.Plugins.Watermark.WatermarkPlugin, ImageResizer.Plugins.WebPDecoder.WebPDecoderPlugin, ImageResizer.Plugins.WebPEncoder.WebPEncoderPlugin, ImageResizer.Plugins.WhitespaceTrimmer.WhitespaceTrimmerPlugin, ImageResizer.Plugins.WicBuilder.WicBuilderPlugin, ImageResizer.Plugins.WicDecoder.WicDecoderPlugin, ImageResizer.Plugins.WicEncoder.WicEncoderPlugin, ImageResizer.Plugins.WpfBuilder.WpfBuilderPlugin, and ImageResizer.Plugins.WpfBuilder.WpfEncoderPlugin.
Public Member Functions
IPlugin Install (Config c)
Installs the plugin in the specified Config instance. The plugin must handle all the work of loading settings, registering the plugin etc.
bool Uninstall (Config c)
Uninstalls the plugin. Should reverse all changes made during Install.
Detailed Description
All plugins must implement this. Enables web.config addition and removal.
Definition at line 11 of file IPlugin.cs.
Member Function Documentation
IPlugin ImageResizer.Plugins.IPlugin.Install (Config c)
Installs the plugin in the specified Config instance. The plugin must handle all the work of loading settings, registering the plugin etc.
Parameters:
c
Returns:
Implemented in ImageResizer.Licensing.LicenseStore, ImageResizer.Licensing.LicenseVerifier, ImageResizer.Plugins.PdfRenderer.PdfRendererPlugin, ImageResizer.Plugins.DiskCache.DiskCache, ImageResizer.Plugins.Basic.VirtualFolder, ImageResizer.Plugins.Basic.Trial, ImageResizer.Plugins.PsdComposer.PsdComposerPlugin, ImageResizer.Plugins.Basic.SizeLimiting, ImageResizer.Plugins.Basic.ImageHandlerSyntax, and ImageResizer.Plugins.WebPEncoder.WebPEncoderPlugin.
Referenced by ImageResizer.Configuration.PluginConfig.GetOrInstall< T >(), and ImageResizer.Configuration.PluginConfig.Install().
bool ImageResizer.Plugins.IPlugin.Uninstall (Config c)
Uninstalls the plugin. Should reverse all changes made during Install.
Parameters:
c
Returns:
Implemented in ImageResizer.Licensing.LicenseStore, ImageResizer.Licensing.LicenseVerifier, ImageResizer.Plugins.PdfRenderer.PdfRendererPlugin, ImageResizer.Plugins.DiskCache.DiskCache, ImageResizer.Plugins.Basic.VirtualFolder, ImageResizer.Plugins.Basic.Trial, ImageResizer.Plugins.PsdComposer.PsdComposerPlugin, ImageResizer.Plugins.Basic.SizeLimiting, and ImageResizer.Plugins.WebPEncoder.WebPEncoderPlugin.
Referenced by ImageResizer.Configuration.PluginConfig.RemoveAll(), and ImageResizer.Configuration.PluginConfig.Uninstall().
The documentation for this interface was generated from the following file:
C:/Users/Administrator/Documents/resizer/Core/Plugins/IPlugin.cs