ImageResizer: ImageResizer.Plugins.IVirtualImageProvider Interface Reference
ImageResizer.Plugins.IVirtualImageProvider Interface Reference
Implement this to allow your class (or VirtualPathProvider subclass) to be used without registering it with the whole ASP.NET system.
Public Member Functions
bool FileExists (string virtualPath, NameValueCollection queryString)
Returns true if the specified file exists.
IVirtualFile GetFile (string virtualPath, NameValueCollection queryString)
Returns a virtual file instance for the specified path and querystring.
Detailed Description
Implement this to allow your class (or VirtualPathProvider subclass) to be used without registering it with the whole ASP.NET system.
Definition at line 11 of file IVirtualImageProvider.cs.
Member Function Documentation
bool ImageResizer.Plugins.IVirtualImageProvider.FileExists (string virtualPath, NameValueCollection queryString)
Returns true if the specified file exists.
Parameters:
virtualPath
queryString
Returns:
Implemented in ImageResizer.Plugins.SqlReader.SqlReaderPlugin, ImageResizer.Configuration.PipelineConfig, ImageResizer.Plugins.Basic.VirtualFolder, ImageResizer.Configuration.IPipelineConfig, and ImageResizer.Plugins.PsdComposer.PsdComposerPlugin.
Referenced by ImageResizer.Configuration.PipelineConfig.FileExists(), and ImageResizer.Configuration.PipelineConfig.GetFile().
IVirtualFile ImageResizer.Plugins.IVirtualImageProvider.GetFile (string virtualPath, NameValueCollection queryString)
Returns a virtual file instance for the specified path and querystring.
Parameters:
virtualPath
queryString
Returns:
Implemented in ImageResizer.Plugins.SqlReader.SqlReaderPlugin, ImageResizer.Configuration.PipelineConfig, ImageResizer.Plugins.Basic.VirtualFolder, ImageResizer.Configuration.IPipelineConfig, and ImageResizer.Plugins.PsdComposer.PsdComposerPlugin.
Referenced by ImageResizer.Configuration.PipelineConfig.GetFile().
The documentation for this interface was generated from the following file:
C:/Users/Administrator/Documents/resizer/Core/Plugins/IVirtualImageProvider.cs