ImageResizer: ImageResizer.Configuration.IPipelineConfig Interface Reference
ImageResizer.Configuration.IPipelineConfig Interface Reference
Public Member Functions
bool IsAcceptedImageType (string filePath)
True if the specified extension is one that the pipeline can handle.
bool HasPipelineDirective (NameValueCollection q)
True if the querystring contains any directives that are understood by the pipeline.
string TrimFakeExtensions (string path)
Removes the first fake extension detected at the end of 'path' (like image.jpg.ashx -> image.jpg).
ImageBuilder GetImageBuilder ()
Returns an ImageBuilder instance to use for image processing.
ICacheProvider GetCacheProvider ()
Returns a ICacheProvider instance that provides caching system selection and creation.
new IVirtualFile GetFile (string virtualPath, NameValueCollection queryString)
new bool FileExists (string virtualPath, NameValueCollection queryString)
Returns true if (a) A registered IVirtualImageProvider says it exists, or (b) if the VirtualPathProvider chain says it exists.
void FirePostAuthorizeRequest (IHttpModule sender, System.Web.HttpContext httpContext)
void FireRewritingEvents (IHttpModule sender, System.Web.HttpContext context, IUrlEventArgs ue)
void FireAuthorizeImage (IHttpModule sender, System.Web.HttpContext context, IUrlAuthorizationEventArgs urlEventArgs)
void FirePreHandleImage (IHttpModule sender, System.Web.HttpContext context, IResponseArgs e)
void FireImageMissing (IHttpModule sender, System.Web.HttpContext context, IUrlEventArgs urlEventArgs)
Properties
string ModifiedQueryStringKey [get]
The key in Context.Items to store the modified querystring (i.e, post-rewrite). Allows VirtualPathProviders to access the rewritten data.
string ResponseArgsKey [get]
The key in Context.Items to store the IResponseArgs object.
string StopRoutingKey [get]
The key in Context.Items to set if we want to cancel MVC routing for the request.
string ModifiedPathKey [get]
The key in Context.Items to access a the path to use instead of Request.path.
VppUsageOption VppUsage [get]
The behavior to use when accessing the file system.
string SkipFileTypeCheckKey [get]
bool SkipFileTypeCheck [get]
Get or sets whether the file extension check should be applied to the current request. Defaults to true. If set to true, will only affect the current request, and will only cause the Resizer to evaluate the rewriting rules on the request. Processing may still not occur if no querystring values are specified. Add 'cache=always' to force caching to occur.
bool ModuleInstalled [get, set]
True once the InterceptModule has been installed.
string PreRewritePath [get]
Returns the value of Context.Items["resizer.newPath"] if present. If not, returns FilePath + PathInfo. Sets Context.Items["resizer.newPath"]. Only useful during the Pipeline.PostAuthorizeRequestStart event.
NameValueCollection ModifiedQueryString [get, set]
Detailed Description
Definition at line 25 of file IPipelineConfig.cs.
Member Function Documentation
new bool ImageResizer.Configuration.IPipelineConfig.FileExists (string virtualPath, NameValueCollection queryString)
Returns true if (a) A registered IVirtualImageProvider says it exists, or (b) if the VirtualPathProvider chain says it exists.
Parameters:
virtualPath
queryString
Returns:
Implements ImageResizer.Plugins.IVirtualImageProvider.
Implemented in ImageResizer.Configuration.PipelineConfig.
ICacheProvider ImageResizer.Configuration.IPipelineConfig.GetCacheProvider ()
Returns a ICacheProvider instance that provides caching system selection and creation.
Returns:
Implemented in ImageResizer.Configuration.PipelineConfig.
new IVirtualFile ImageResizer.Configuration.IPipelineConfig.GetFile (string virtualPath, NameValueCollection queryString)
Returns an IVirtualFile instance if the specified file exists.
Parameters:
virtualPath
queryString
Returns:
Implements ImageResizer.Plugins.IVirtualImageProvider.
Implemented in ImageResizer.Configuration.PipelineConfig.
Referenced by ImageResizer.InterceptModule.CheckRequest_PostAuthorizeRequest().
ImageBuilder ImageResizer.Configuration.IPipelineConfig.GetImageBuilder ()
Returns an ImageBuilder instance to use for image processing.
Returns:
Implemented in ImageResizer.Configuration.PipelineConfig.
Referenced by ImageResizer.InterceptModule.HandleRequest().
bool ImageResizer.Configuration.IPipelineConfig.HasPipelineDirective (NameValueCollection q)
True if the querystring contains any directives that are understood by the pipeline.
Parameters:
q
Returns:
Referenced by ImageResizer.InterceptModule.CheckRequest_PostAuthorizeRequest(), and ImageResizer.InterceptModule.HandleRequest().
bool ImageResizer.Configuration.IPipelineConfig.IsAcceptedImageType (string filePath)
True if the specified extension is one that the pipeline can handle.
Parameters:
filePath
Returns:
Implemented in ImageResizer.Configuration.PipelineConfig.
Referenced by ImageResizer.InterceptModule.CheckRequest_PostAuthorizeRequest(), and ImageResizer.InterceptModule.HandleRequest().
string ImageResizer.Configuration.IPipelineConfig.TrimFakeExtensions (string path)
Removes the first fake extension detected at the end of 'path' (like image.jpg.ashx -> image.jpg).
Parameters:
path
Returns:
Implemented in ImageResizer.Configuration.PipelineConfig.
Referenced by ImageResizer.InterceptModule.CheckRequest_PostAuthorizeRequest().
Property Documentation
string ImageResizer.Configuration.IPipelineConfig.ModifiedPathKey [get]
The key in Context.Items to access a the path to use instead of Request.path.
Implemented in ImageResizer.Configuration.PipelineConfig.
Definition at line 58 of file IPipelineConfig.cs.
string ImageResizer.Configuration.IPipelineConfig.ModifiedQueryStringKey [get]
The key in Context.Items to store the modified querystring (i.e, post-rewrite). Allows VirtualPathProviders to access the rewritten data.
Implemented in ImageResizer.Configuration.PipelineConfig.
Definition at line 43 of file IPipelineConfig.cs.
bool ImageResizer.Configuration.IPipelineConfig.ModuleInstalled [get, set]
True once the InterceptModule has been installed.
Implemented in ImageResizer.Configuration.PipelineConfig.
Definition at line 75 of file IPipelineConfig.cs.
string ImageResizer.Configuration.IPipelineConfig.PreRewritePath [get]
Returns the value of Context.Items["resizer.newPath"] if present. If not, returns FilePath + PathInfo. Sets Context.Items["resizer.newPath"]. Only useful during the Pipeline.PostAuthorizeRequestStart event.
Implemented in ImageResizer.Configuration.PipelineConfig.
Definition at line 82 of file IPipelineConfig.cs.
Referenced by ImageResizer.InterceptModule.CheckRequest_PostAuthorizeRequest().
string ImageResizer.Configuration.IPipelineConfig.ResponseArgsKey [get]
The key in Context.Items to store the IResponseArgs object.
Implemented in ImageResizer.Configuration.PipelineConfig.
Definition at line 48 of file IPipelineConfig.cs.
Referenced by ImageResizer.InterceptModule.HandleRequest().
bool ImageResizer.Configuration.IPipelineConfig.SkipFileTypeCheck [get]
Get or sets whether the file extension check should be applied to the current request. Defaults to true. If set to true, will only affect the current request, and will only cause the Resizer to evaluate the rewriting rules on the request. Processing may still not occur if no querystring values are specified. Add 'cache=always' to force caching to occur.
Implemented in ImageResizer.Configuration.PipelineConfig.
Definition at line 70 of file IPipelineConfig.cs.
Referenced by ImageResizer.InterceptModule.CheckRequest_PostAuthorizeRequest().
string ImageResizer.Configuration.IPipelineConfig.StopRoutingKey [get]
The key in Context.Items to set if we want to cancel MVC routing for the request.
Implemented in ImageResizer.Configuration.PipelineConfig.
Definition at line 53 of file IPipelineConfig.cs.
Referenced by ImageResizer.InterceptModule.HandleRequest().
VppUsageOption ImageResizer.Configuration.IPipelineConfig.VppUsage [get]
The behavior to use when accessing the file system.
Implemented in ImageResizer.Configuration.PipelineConfig.
Definition at line 62 of file IPipelineConfig.cs.
Referenced by ImageResizer.InterceptModule.CheckRequest_PostAuthorizeRequest().
The documentation for this interface was generated from the following file:
C:/Users/Administrator/Documents/resizer/Core/Configuration/IPipelineConfig.cs